#include "\userconfig\arc_ai\macros.hpp"
#include "macros.hpp"

class CfgPatches {
    class arc_ai_client_launchers {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1.54;
        author[] = {"Ed", "Kingsley"};
        authorUrl = "https://github.com/ARCOMM/ARC_AI";
        requiredAddons[] = {"arc_ai_main"};
        ammo[] = {};
    };
};

class CfgAmmo {
    PROTO(Default);
    LAUNCHER(MissileCore, Default);
    LAUNCHER(BombCore, Default);
    LAUNCHER(LaserBombCore, BombCore);
    LAUNCHER(MissileBase, MissileCore);
    LAUNCHER(ammo_Missile_CannonLaunchedBase, MissileBase);
    LAUNCHER(ammo_Bomb_LaserGuidedBase, LaserBombCore);
    LAUNCHER(M_PG_AT, MissileBase);
    LAUNCHER(M_NLAW_AT_F, MissileBase);
    LAUNCHER(M_Scalpel_AT, MissileBase);
    LAUNCHER(M_Scalpel_AT_hidden, M_Scalpel_AT);
    LAUNCHER(Bo_Air_LGB, M_Scalpel_AT);
    LAUNCHER(Bo_Air_LGB_hidden, M_Scalpel_AT_hidden);
    LAUNCHER(Bo_GBU12_LGB, ammo_Bomb_LaserGuidedBase);
    LAUNCHER(Bo_GBU12_LGB_MI10, Bo_GBU12_LGB);
    LAUNCHER(Bomb_03_F, ammo_Bomb_LaserGuidedBase);
    LAUNCHER(Bomb_04_F, ammo_Bomb_LaserGuidedBase);
    LAUNCHER(Bo_Mk82, BombCore);
    LAUNCHER(Bo_Mk82_MI08, Bo_Mk82);
    PROTO(RocketBase);
    LAUNCHER(R_80mm_HE, RocketBase);
    LAUNCHER(R_60mm_HE, R_80mm_HE);
    LAUNCHER(M_Titan_AA, MissileBase);
    LAUNCHER(M_Titan_AA_static, M_Titan_AA);
    LAUNCHER(M_Titan_AA_long, M_Titan_AA);
    LAUNCHER(M_Zephyr, M_Titan_AA);
    LAUNCHER(M_Zephyr_Mi06, M_Zephyr);
    LAUNCHER(M_Zephyr_air, M_Zephyr);
    LAUNCHER(M_Air_AA, MissileBase);
    LAUNCHER(M_Air_AA_MI02, M_Air_AA);
    LAUNCHER(M_Air_AA_MI06, M_Air_AA);
    LAUNCHER(M_Titan_AT, MissileBase);
    LAUNCHER(M_Titan_AP, M_Titan_AT);
    LAUNCHER(M_Titan_AT_static, M_Titan_AT);
    LAUNCHER(M_Titan_AT_long, M_Titan_AT);
    LAUNCHER(M_Air_AT, M_Titan_AT);
    LAUNCHER(Missile_AA_04_F, MissileBase);
    LAUNCHER(Missile_AGM_02_F, MissileBase);
    LAUNCHER(M_Mo_82mm_AT, MissileBase);
    LAUNCHER(M_Mo_82mm_AT_LG, M_Mo_82mm_AT);
    LAUNCHER(M_Mo_120mm_AT, M_Mo_82mm_AT);
    LAUNCHER(M_Mo_120mm_AT_LG, M_Mo_120mm_AT);
    LAUNCHER(M_Mo_155mm_AT, M_Mo_120mm_AT);
    LAUNCHER(M_Mo_155mm_AT_LG, M_Mo_120mm_AT_LG);
    LAUNCHER(M_Mo_230mm_AT_LG, M_Mo_155mm_AT_LG);
    LAUNCHER(M_Mo_230mm_AT, M_Mo_155mm_AT);
    LAUNCHER(Rocket_04_HE_F, MissileBase);
    LAUNCHER(Rocket_04_AP_F, Rocket_04_HE_F);
    LAUNCHER(Missile_AA_03_F, Missile_AA_04_F);
    LAUNCHER(Missile_AGM_01_F, Missile_AGM_02_F);
    LAUNCHER(Rocket_03_HE_F, Rocket_04_HE_F);
    LAUNCHER(Rocket_03_AP_F, Rocket_04_AP_F);
    LAUNCHER(M_Jian_AT, Missile_AGM_01_F);
    LAUNCHER(ammo_Missile_MediumRangeAABase, MissileBase);
    LAUNCHER(ammo_Missile_ShortRangeAABase, MissileBase);
    LAUNCHER(ammo_Missile_rim116, ammo_Missile_ShortRangeAABase);
    LAUNCHER(ammo_Missile_rim162, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AMRAAM_C, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AMRAAM_D, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_BIM9X, ammo_Missile_ShortRangeAABase);
    LAUNCHER(ammo_Missile_AA_R77, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AA_R73, ammo_Missile_ShortRangeAABase);
    LAUNCHER(BombDemine_01_Ammo_F, BombCore);
    LAUNCHER(BombDemine_01_DummyAmmo_F, BombDemine_01_Ammo_F);
    LAUNCHER(Bo_Leaflets, BombCore);
    LAUNCHER(BombCluster_01_Ammo_F, Bomb_04_F);
    LAUNCHER(BombCluster_02_Ammo_F, BombCluster_01_Ammo_F);
    LAUNCHER(BombCluster_02_Cap_Ammo_F, BombCluster_02_Ammo_F);
    LAUNCHER(BombCluster_03_Ammo_F, BombCluster_01_Ammo_F);
    LAUNCHER(M_125mm_cannon_ATGM, ammo_Missile_CannonLaunchedBase);
    LAUNCHER(M_120mm_cannon_ATGM, ammo_Missile_CannonLaunchedBase);
    LAUNCHER(M_120mm_cannon_ATGM_LG, M_120mm_cannon_ATGM);
    LAUNCHER(M_Vorona_HEAT, MissileBase);
    LAUNCHER(M_Vorona_HE, M_Vorona_HEAT);
    LAUNCHER(M_127mm_Firefist_AT, MissileBase);
    LAUNCHER(M_70mm_SAAMI, MissileBase);
    LAUNCHER(ACE_Hellfire_AGM114K, M_PG_AT);
    LAUNCHER(ACE_Hydra70_DAGR, M_PG_AT);
    LAUNCHER(ACE_Javelin_FGM148, M_Titan_AT);
    LAUNCHER(ACE_Javelin_FGM148_static, ACE_Javelin_FGM148);
    LAUNCHER(ACE_NLAW, M_NLAW_AT_F);
    LAUNCHER(ACE_NLAW_Explosion, ACE_NLAW);
    LAUNCHER(ACE_NLAW_ShapedCharge, ACE_NLAW);
    LAUNCHER(ACE_Hellfire_AGM114N, ACE_Hellfire_AGM114K);
    LAUNCHER(ace_maverick_L, Missile_AGM_02_F);
    LAUNCHER(ace_kh25ml, Missile_AGM_01_F);
};
