#include "\userconfig\arc_ai\macros.hpp"
#include "macros.hpp"

class CfgPatches {
    class arc_ai_client_launchers {
        units[] = {};
        weapons[] = {};
        requiredVersion = 1.54;
        author[] = {"Ed", "Kingsley"};
        authorUrl = "https://github.com/ARCOMM/ARC_AI";
        requiredAddons[] = {"arc_ai_main"};
        ammo[] = {};
    };
};

class CfgAmmo {
    PROTO(Default);
    LAUNCHER(MissileCore, Default);
    LAUNCHER(BombCore, Default);
    LAUNCHER(LaserBombCore, BombCore);
    LAUNCHER(MissileBase, MissileCore);
    LAUNCHER(M_PG_AT, MissileBase);
    LAUNCHER(M_AT, M_PG_AT);
    LAUNCHER(M_NLAW_AT_F, MissileBase);
    LAUNCHER(M_Scalpel_AT, MissileBase);
    LAUNCHER(M_Scalpel_AT_hidden, M_Scalpel_AT);
    LAUNCHER(Bo_Air_LGB, M_Scalpel_AT);
    LAUNCHER(Bo_Air_LGB_hidden, M_Scalpel_AT_hidden);
    LAUNCHER(Bo_GBU12_LGB, LaserBombCore);
    LAUNCHER(Bo_GBU12_LGB_MI10, Bo_GBU12_LGB);
    PROTO(RocketBase);
    LAUNCHER(R_80mm_HE, RocketBase);
    LAUNCHER(R_60mm_HE, R_80mm_HE);
    LAUNCHER(M_Titan_AA, MissileBase);
    LAUNCHER(M_Zephyr, M_Titan_AA);
    LAUNCHER(M_Zephyr_Mi06, M_Zephyr);
    LAUNCHER(M_Titan_AA_long, M_Titan_AA);
    LAUNCHER(M_Air_AA, MissileBase);
    LAUNCHER(M_Air_AA_MI02, M_Air_AA);
    LAUNCHER(M_Air_AA_MI06, M_Air_AA);
    LAUNCHER(M_Titan_AT, MissileBase);
    LAUNCHER(M_Titan_AP, M_Titan_AT);
    LAUNCHER(M_Air_AT, M_Titan_AT);
    LAUNCHER(M_Zephyr_air, M_Zephyr);
    LAUNCHER(M_Titan_AA_static, M_Titan_AA);
    LAUNCHER(M_Titan_AT_static, M_Titan_AT);
    LAUNCHER(Missile_AA_04_F, MissileBase);
    LAUNCHER(Missile_AGM_02_F, MissileBase);
    LAUNCHER(Bomb_04_F, LaserBombCore);
    LAUNCHER(M_Mo_82mm_AT, MissileBase);
    LAUNCHER(M_Mo_82mm_AT_LG, M_Mo_82mm_AT);
    LAUNCHER(M_Mo_120mm_AT, M_Mo_82mm_AT);
    LAUNCHER(M_Mo_120mm_AT_LG, M_Mo_120mm_AT);
    LAUNCHER(M_Mo_155mm_AT, M_Mo_120mm_AT);
    LAUNCHER(M_Mo_155mm_AT_LG, M_Mo_120mm_AT_LG);
    LAUNCHER(Rocket_04_HE_F, MissileBase);
    LAUNCHER(Rocket_04_AP_F, Rocket_04_HE_F);
    LAUNCHER(Missile_AA_03_F, Missile_AA_04_F);
    LAUNCHER(Missile_AGM_01_F, Missile_AGM_02_F);
    LAUNCHER(Bomb_03_F, Bomb_04_F);
    LAUNCHER(Rocket_03_HE_F, Rocket_04_HE_F);
    LAUNCHER(Rocket_03_AP_F, Rocket_04_AP_F);
    LAUNCHER(M_RIM_116, M_Air_AA);
    LAUNCHER(M_RIM_7, M_RIM_116);
    LAUNCHER(CUP_M_9K32_Strela_2_AA, M_Titan_AA);
    LAUNCHER(CUP_M_9K38_Igla_AA, M_Titan_AA);
    LAUNCHER(CUP_M_9M311_Tunguska_AA, M_Titan_AA);
    LAUNCHER(CUP_M_9M311M_Tunguska_AA, CUP_M_9M311_Tunguska_AA);
    LAUNCHER(CUP_M_3M11_AT2_Falanga_AT, MissileBase);
    LAUNCHER(CUP_M_9K11_AT3_Sagger_AT, MissileBase);
    LAUNCHER(CUP_M_9M113_AT5_Spandrel_AT, MissileBase);
    LAUNCHER(CUP_M_Shturm_9K114_AT6_Spiral_AT, MissileBase);
    LAUNCHER(CUP_M_Ataka_V_9M120_AT9_Spiral_2_AT, MissileBase);
    LAUNCHER(CUP_M_9K116_1_Bastion_AT10_Stabber_AT, MissileBase);
    LAUNCHER(CUP_M_9M119M_Bastion_AT11_Sniper_AT, MissileBase);
    LAUNCHER(CUP_M_9K115_2_AT13_Saxhorn_2_AT, M_Titan_AT);
    LAUNCHER(CUP_M_9K121_Vikhr_AT16_Scallion_AT, MissileBase);
    LAUNCHER(CUP_M_KH29L_AT, M_Scalpel_AT);
    LAUNCHER(CUP_M_AGM_114K_Hellfire_II_AT, MissileBase);
    LAUNCHER(CUP_M_AGM_114L_Hellfire_II_AT, MissileBase);
    LAUNCHER(CUP_M_AIM_9L_Sidewinder_AA, MissileBase);
    LAUNCHER(CUP_M_AIM_9L_Sidewinder_AA_INTERNAL, CUP_M_AIM_9L_Sidewinder_AA);
    LAUNCHER(CUP_M_Stinger_AA, MissileBase);
    LAUNCHER(CUP_M_RBS70_AA, MissileBase);
    LAUNCHER(CUP_AGM65pod_AT, MissileBase);
    LAUNCHER(CUP_AGM65_AT, CUP_AGM65pod_AT);
    LAUNCHER(CUP_AGM84_AT, MissileBase);
    LAUNCHER(CUP_R_TOW_AT, M_Titan_AT);
    LAUNCHER(CUP_R_TOW2_AT, CUP_R_TOW_AT);
    LAUNCHER(CUP_M_Javelin_AT, MissileBase);
    LAUNCHER(CUP_M_47_AT_EP1, MissileBase);
    LAUNCHER(CUP_M_NLAW_AT, MissileBase);
    LAUNCHER(CUP_Bo_GBU12_LGB, Bo_GBU12_LGB);
    LAUNCHER(CUP_Bo_KAB250_LGB, Bo_GBU12_LGB);
    LAUNCHER(CUP_Triple_Bomb_Rack_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Dual_Bomb_Rack_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_AGM_Rack_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_AGM_Dual_Rack_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_7_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_19_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_7_Dummy_Full, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_19_Dummy_Full, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_7_Dummy_Mount, Bo_GBU12_LGB);
    LAUNCHER(CUP_Hydra_Pod_19_Dummy_Mount, Bo_GBU12_LGB);
    LAUNCHER(CUP_CRV7_Pod_12_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_CRV7_Pod_19_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_AT2_Rack_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_AT6_Tube_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_AT6_Rackcomplete_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Ataka_Tube_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Ataka_Rackcomplete_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_S5_Pod_Small_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_S5_Pod_Big_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_S8_Pod_Heli_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_S8_Pod_Air_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Igla_Rack_Twin_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Vikhr_Rack_6rnd_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Sidewinder_Rack_2Rnd_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_Litening, MissileBase);
    LAUNCHER(CUP_ALQ131, MissileBase);
    LAUNCHER(CUP_pylonblank, MissileBase);
    LAUNCHER(CUP_GSH23_gunpod_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_M621_gunpod_Dummy, Bo_GBU12_LGB);
    LAUNCHER(CUP_S13_Pod_Heli_Dummy, Bo_GBU12_LGB);
    LAUNCHER(M_Jian_AT, Missile_AGM_01_F);
    LAUNCHER(ammo_Missile_MediumRangeAABase, MissileBase);
    LAUNCHER(ammo_Missile_ShortRangeAABase, MissileBase);
    LAUNCHER(ammo_Missile_rim116, ammo_Missile_ShortRangeAABase);
    LAUNCHER(ammo_Missile_rim162, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AMRAAM_C, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AMRAAM_D, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_BIM9X, ammo_Missile_ShortRangeAABase);
    LAUNCHER(ammo_Missile_AA_R77, ammo_Missile_MediumRangeAABase);
    LAUNCHER(ammo_Missile_AA_R73, ammo_Missile_ShortRangeAABase);
    LAUNCHER(BombDemine_01_Ammo_F, BombCore);
    LAUNCHER(BombDemine_01_DummyAmmo_F, BombDemine_01_Ammo_F);
    LAUNCHER(Bo_Leaflets, BombCore);
    LAUNCHER(BombCluster_01_Ammo_F, Bomb_04_F);
    LAUNCHER(BombCluster_02_Ammo_F, BombCluster_01_Ammo_F);
    LAUNCHER(BombCluster_02_Cap_Ammo_F, BombCluster_02_Ammo_F);
    LAUNCHER(BombCluster_03_Ammo_F, BombCluster_01_Ammo_F);
    LAUNCHER(ACE_Hellfire_AGM114K, M_PG_AT);
    LAUNCHER(ACE_Hydra70_DAGR, M_PG_AT);
    LAUNCHER(ACE_Javelin_FGM148, M_Titan_AT);
    LAUNCHER(ACE_Javelin_FGM148_static, ACE_Javelin_FGM148);
    LAUNCHER(ACE_NLAW, M_NLAW_AT_F);
    LAUNCHER(ACE_NLAW_Explosion, ACE_NLAW);
    LAUNCHER(ACE_NLAW_ShapedCharge, ACE_NLAW);
    LAUNCHER(BombBase, BombCore);
    LAUNCHER(ACE_Hellfire_AGM114N, ACE_Hellfire_AGM114K);
    LAUNCHER(ace_maverick_L, Missile_AGM_02_F);
    LAUNCHER(rhs_ammo_M_fgm148_AT, MissileBase);
};
