class CfgAmmo {
    PROTO(Grenade);
    GRENADE(GrenadeHand, Grenade);
    GRENADE(mini_Grenade, GrenadeHand);
    GRENADE(SmokeShell, GrenadeHand);
    GRENADE(SmokeShellRed, SmokeShell);
    GRENADE(SmokeShellGreen, SmokeShell);
    GRENADE(SmokeShellYellow, SmokeShell);
    GRENADE(SmokeShellPurple, SmokeShell);
    GRENADE(SmokeShellBlue, SmokeShell);
    GRENADE(SmokeShellOrange, SmokeShell);
    PROTO(Chemlight_base);
    GRENADE(Chemlight_green, Chemlight_base);
    GRENADE(Chemlight_red, Chemlight_base);
    GRENADE(Chemlight_yellow, Chemlight_base);
    GRENADE(Chemlight_blue, Chemlight_base);
    GRENADE(rhs_ammo_rgd5, GrenadeHand);
    PROTO(rhs_ammo_rgn_base);
    GRENADE(rhs_ammo_rgn, rhs_ammo_rgn_base);
    GRENADE(rhs_ammo_rdg2_white, SmokeShell);
    GRENADE(rhs_ammo_rdg2_black, rhs_ammo_rdg2_white);
    GRENADE(rhs_ammo_nspn_yellow, rhs_ammo_rdg2_white);
    GRENADE(rhs_ammo_nspn_red, rhs_ammo_nspn_yellow);
    GRENADE(rhs_ammo_nspn_green, rhs_ammo_nspn_yellow);
    GRENADE(rhs_ammo_nspd, rhs_ammo_rdg2_white);
    GRENADE(rhs_ammo_m67, GrenadeHand);
    GRENADE(rhs_ammo_an_m8hc, SmokeShell);
    GRENADE(rhs_ammo_mk3a2, GrenadeHand);
    GRENADE(rhs_ammo_m18_green, SmokeShell);
    GRENADE(rhs_ammo_m18_purple, rhs_ammo_m18_green);
    GRENADE(rhs_ammo_m18_red, rhs_ammo_m18_green);
    GRENADE(rhs_ammo_m18_yellow, rhs_ammo_m18_green);
    GRENADE(ACE_G_Handflare_White, SmokeShell);
    GRENADE(ACE_G_Handflare_Red, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Green, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Yellow, ACE_G_Handflare_White);
    GRENADE(ACE_G_M84, SmokeShell);
    GRENADE(ACE_G_M14, SmokeShell);
    GRENADE(ACE_G_Chemlight_Orange, Chemlight_base);
    GRENADE(ACE_G_Chemlight_White, Chemlight_base);
    GRENADE(ACE_G_Chemlight_HiRed, Chemlight_red);
    GRENADE(ACE_G_Chemlight_HiYellow, Chemlight_yellow);
    GRENADE(ACE_G_Chemlight_HiOrange, ACE_G_Chemlight_Orange);
    GRENADE(ACE_G_Chemlight_HiWhite, ACE_G_Chemlight_White);
    GRENADE(ACE_G_Chemlight_IR, Chemlight_base);
};

class CfgWeapons {
    PROTO(DMR_01_base_F);
    RIFLE(srifle_DMR_01_F, DMR_01_base_F);
    RIFLE(srifle_DMR_01_ACO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_ARCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_snds_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_MRCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_SOS_F, srifle_DMR_01_F);
    PROTO(EBR_base_F);
    RIFLE(srifle_EBR_F, EBR_base_F);
    RIFLE(srifle_EBR_ACO_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_Hamr_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_MRCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_SOS_F, srifle_EBR_F);
    PROTO(GM6_base_F);
    RIFLE(srifle_GM6_F, GM6_base_F);
    RIFLE(srifle_GM6_camo_F, srifle_GM6_F);
    RIFLE(srifle_GM6_camo_LRPS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_camo_SOS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_LRPS_F, srifle_GM6_F);
    RIFLE(srifle_GM6_SOS_F, srifle_GM6_F);
    PROTO(LRR_base_F);
    RIFLE(srifle_LRR_F, LRR_base_F);
    RIFLE(srifle_LRR_camo_F, srifle_LRR_F);
    RIFLE(srifle_LRR_camo_LRPS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_camo_SOS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_LRPS_F, srifle_LRR_F);
    RIFLE(srifle_LRR_SOS_F, srifle_LRR_F);
    PROTO(Rifle_Long_Base_F);
    MG(LMG_Mk200_F, Rifle_Long_Base_F);
    MG(LMG_Mk200_MRCO_F, LMG_Mk200_F);
    MG(LMG_Mk200_pointer_F, LMG_Mk200_F);
    MG(LMG_Zafir_F, Rifle_Long_Base_F);
    MG(LMG_Zafir_ARCO_F, LMG_Zafir_F);
    MG(LMG_Zafir_pointer_F, LMG_Zafir_F);
    PROTO(arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_ACO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_C_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_C_ACO_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_snds_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_GL_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_GL_ACO_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_snds_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ARCO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_Nstalker_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_pointer_F, arifle_Katiba_F);
    PROTO(mk20_base_F);
    RIFLE(arifle_Mk20_F, mk20_base_F);
    RIFLE(arifle_Mk20_ACO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_ACO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_GL_F, mk20_base_F);
    RIFLE(arifle_Mk20_GL_ACO_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_MRCO_pointer_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_plain_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_Holo_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_plain_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_plain_F, arifle_Mk20_plain_F);
    RIFLE(arifle_Mk20_MRCO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20C_F, mk20_base_F);
    RIFLE(arifle_Mk20C_ACO_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_ACO_pointer_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_plain_F, arifle_Mk20C_F);
    PROTO(arifle_MX_Base_F);
    RIFLE(arifle_MX_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_ACO_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_GL_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_GL_ACO_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_ACO_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Hamr_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Holo_pointer_snds_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_Hamr_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_Holo_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_RCO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_SW_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_SW_Hamr_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MXC_F, arifle_MX_Base_F);
    RIFLE(arifle_MXC_ACO_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_SOS_point_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXM_F, arifle_MX_Base_F);
    RIFLE(arifle_MXM_DMS_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MXM_RCO_pointer_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_SOS_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MX_Black_F, arifle_MX_F);
    RIFLE(arifle_MX_Black_Hamr_pointer_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_GL_Black_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Black_Hamr_pointer_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_SW_Black_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_Black_Hamr_pointer_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MXC_Black_F, arifle_MXC_F);
    RIFLE(arifle_MXM_Black_F, arifle_MXM_F);
    PROTO(SDAR_base_F);
    RIFLE(arifle_SDAR_F, SDAR_base_F);
    PROTO(Tavor_base_F);
    RIFLE(arifle_TRG20_F, Tavor_base_F);
    RIFLE(arifle_TRG20_ACO_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_Flash_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_pointer_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_Holo_F, arifle_TRG20_F);
    RIFLE(arifle_TRG21_F, Tavor_base_F);
    RIFLE(arifle_TRG21_ACO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_ARCO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_ACO_pointer_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_GL_MRCO_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_MRCO_F, arifle_TRG21_F);
    PROTO(pdw2000_base_F);
    RIFLE(hgun_PDW2000_F, pdw2000_base_F);
    RIFLE(hgun_PDW2000_Holo_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_Holo_snds_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_snds_F, hgun_PDW2000_F);
    PROTO(SMG_01_Base);
    RIFLE(SMG_01_F, SMG_01_Base);
    RIFLE(SMG_01_ACO_F, SMG_01_F);
    RIFLE(SMG_01_Holo_F, SMG_01_F);
    RIFLE(SMG_01_Holo_pointer_snds_F, SMG_01_F);
    PROTO(SMG_02_base_F);
    RIFLE(SMG_02_F, SMG_02_base_F);
    RIFLE(SMG_02_ACO_F, SMG_02_F);
    RIFLE(SMG_02_ARCO_pointg_F, SMG_02_F);
    RIFLE(srifle_DMR_01_DMS_BI_F, srifle_DMR_01_DMS_F);
    RIFLE(srifle_DMR_01_DMS_snds_BI_F, srifle_DMR_01_DMS_snds_F);
    PROTO(DMR_02_base_F);
    RIFLE(srifle_DMR_02_F, DMR_02_base_F);
    RIFLE(srifle_DMR_02_ACO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_ARCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_AMS_LP_F, srifle_DMR_02_camo_F);
    RIFLE(srifle_DMR_02_DMS_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_MRCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_AMS_LP_S_F, srifle_DMR_02_sniper_F);
    RIFLE(srifle_DMR_02_SOS_F, srifle_DMR_02_F);
    PROTO(DMR_03_base_F);
    RIFLE(srifle_DMR_03_F, DMR_03_base_F);
    RIFLE(srifle_DMR_03_ACO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_AMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_ARCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_snds_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_khaki_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_MRCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_multicam_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_SOS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_AMS_LP_F, srifle_DMR_03_tan_F);
    RIFLE(srifle_DMR_03_woodland_F, srifle_DMR_03_F);
    PROTO(DMR_04_base_F);
    RIFLE(srifle_DMR_04_F, DMR_04_base_F);
    RIFLE(srifle_DMR_04_ACO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_ARCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_DMS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_MRCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_NS_LP_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_SOS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_Tan_F, srifle_DMR_04_F);
    PROTO(DMR_05_base_F);
    RIFLE(srifle_DMR_05_blk_F, DMR_05_base_F);
    RIFLE(srifle_DMR_05_ACO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_ARCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_snds_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_hex_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_KHS_LP_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_MRCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_SOS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_tan_f, srifle_DMR_05_blk_F);
    PROTO(DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_F, DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_khs_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_DMR_06_olive_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_EBR_MRCO_LP_BI_F, srifle_EBR_F);
    MG(LMG_Mk200_BI_F, LMG_Mk200_F);
    MG(LMG_Mk200_LP_BI_F, LMG_Mk200_pointer_F);
    PROTO(MMG_01_base_F);
    MG(MMG_01_hex_F, MMG_01_base_F);
    MG(MMG_01_hex_ARCO_LP_F, MMG_01_hex_F);
    MG(MMG_01_tan_F, MMG_01_hex_F);
    PROTO(MMG_02_base_F);
    MG(MMG_02_camo_F, MMG_02_base_F);
    MG(MMG_02_black_F, MMG_02_camo_F);
    MG(MMG_02_black_RCO_BI_F, MMG_02_black_F);
    MG(MMG_02_sand_F, MMG_02_camo_F);
    MG(MMG_02_sand_RCO_LP_F, MMG_02_sand_F);
    RIFLE(arifle_MXM_DMS_LP_BI_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_LP_BI_F, arifle_MXM_Hamr_pointer_F);
    PROTO(rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74, rhs_weap_ak74m);
    RIFLE(rhs_weap_aks74, rhs_weap_ak74);
    RIFLE(rhs_weap_aks74_2, rhs_weap_aks74);
    RIFLE(rhs_weap_aks74_gp25, rhs_weap_aks74);
    RIFLE(rhs_weap_aks74n, rhs_weap_aks74);
    RIFLE(rhs_weap_aks74n_gp25, rhs_weap_aks74_gp25);
    RIFLE(rhs_weap_aks74u, rhs_weap_aks74);
    RIFLE(rhs_weap_aks74un, rhs_weap_aks74u);
    RIFLE(rhs_weap_ak74_gp25, rhs_weap_ak74);
    RIFLE(rhs_weap_ak74n, rhs_weap_ak74);
    RIFLE(rhs_weap_ak74n_gp25, rhs_weap_ak74_gp25);
    RIFLE(rhs_weap_ak74n_gp25_npz, rhs_weap_ak74_gp25);
    RIFLE(rhs_weap_ak74n_npz, rhs_weap_ak74);
    RIFLE(rhs_weap_ak74_2, rhs_weap_ak74);
    RIFLE(rhs_weap_ak74_3, rhs_weap_ak74);
    PROTO(rhs_weap_ak74m_Base_F);
    RIFLE(rhs_weap_ak74m_plummag, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_camo, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_desert, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_gp25, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_2mag, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_2mag_camo, rhs_weap_ak74m_2mag);
    RIFLE(rhs_weap_ak74m_npz, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_plummag_npz, rhs_weap_ak74m_npz);
    RIFLE(rhs_weap_ak74m_camo_npz, rhs_weap_ak74m_npz);
    RIFLE(rhs_weap_ak74m_desert_npz, rhs_weap_ak74m_npz);
    RIFLE(rhs_weap_ak74m_2mag_npz, rhs_weap_ak74m_2mag);
    RIFLE(rhs_weap_ak74m_2mag_camo_npz, rhs_weap_ak74m_2mag_npz);
    RIFLE(rhs_weap_ak74m_gp25_npz, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_ak74m_fullplum, rhs_weap_ak74m);
    RIFLE(rhs_weap_asval, rhs_weap_ak74m);
    RIFLE(rhs_weap_asval_grip, rhs_weap_asval);
    RIFLE(rhs_weap_asval_grip_npz, rhs_weap_asval_grip);
    RIFLE(rhs_weap_asval_npz, rhs_weap_asval);
    RIFLE(rhs_weap_vss, rhs_weap_asval);
    RIFLE(rhs_weap_vss_grip, rhs_weap_vss);
    RIFLE(rhs_weap_vss_grip_npz, rhs_weap_vss);
    RIFLE(rhs_weap_vss_npz, rhs_weap_vss);
    RIFLE(rhs_weap_akm, rhs_weap_ak74m);
    RIFLE(rhs_weap_akm_gp25, rhs_weap_akm);
    RIFLE(rhs_weap_akmn, rhs_weap_akm);
    RIFLE(rhs_weap_akmn_npz, rhs_weap_akmn);
    RIFLE(rhs_weap_akmn_gp25, rhs_weap_akmn);
    RIFLE(rhs_weap_akmn_gp25_npz, rhs_weap_akmn_gp25);
    RIFLE(rhs_weap_akm_zenitco01_b33, rhs_weap_akmn);
    RIFLE(rhs_weap_akms, rhs_weap_akm);
    RIFLE(rhs_weap_akms_gp25, rhs_weap_akm);
    RIFLE(rhs_weap_pm63, rhs_weap_akm);
    PROTO(rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak103, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak103_npz, rhs_weap_ak103);
    RIFLE(rhs_weap_ak103_1, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak103_1_npz, rhs_weap_ak103_1);
    RIFLE(rhs_weap_ak103_2, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak103_2_npz, rhs_weap_ak103_2);
    RIFLE(rhs_weap_ak103_gp25, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak103_gp25_npz, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak104, rhs_weap_ak103_base);
    RIFLE(rhs_weap_ak104_npz, rhs_weap_ak104);
    RIFLE(rhs_weap_ak105, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak105_npz, rhs_weap_ak105);
    PROTO(rhs_weap_svd);
    RIFLE(rhs_weap_svdp, rhs_weap_svd);
    RIFLE(rhs_weap_svdp_wd, rhs_weap_svdp);
    RIFLE(rhs_weap_svds, rhs_weap_svdp);
    RIFLE(rhs_weap_svdp_npz, rhs_weap_svdp);
    RIFLE(rhs_weap_svdp_wd_npz, rhs_weap_svdp_wd);
    RIFLE(rhs_weap_svds_npz, rhs_weap_svds);
    PROTO(rhs_pkp_base);
    MG(rhs_weap_pkp, rhs_pkp_base);
    MG(rhs_weap_pkm, rhs_weap_pkp);
    RIFLE(rhs_weap_pp2000, hgun_PDW2000_F);
    RIFLE(rhs_weap_ak74m_dtk, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_pkas, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_1p63, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_pso1m2, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_1p29, rhs_weap_ak74m);
    RIFLE(rhs_weap_ak74m_camo_dtk, rhs_weap_ak74m_camo);
    RIFLE(rhs_weap_ak74m_npz_dtk, rhs_weap_ak74m_npz);
    RIFLE(rhs_weap_ak103_dtk, rhs_weap_ak103);
    RIFLE(rhs_weap_ak103_npz_dtk, rhs_weap_ak103_npz);
    RIFLE(rhs_weap_ak103_1_dtk, rhs_weap_ak103_1);
    RIFLE(rhs_weap_ak103_2_dtk, rhs_weap_ak103_2);
    RIFLE(rhs_weap_ak74m_2mag_dtk, rhs_weap_ak74m_2mag);
    RIFLE(rhs_weap_ak74m_2mag_camo_dtk, rhs_weap_ak74m_2mag_camo);
    RIFLE(rhs_weap_ak74m_camo_pkas, rhs_weap_ak74m_camo);
    RIFLE(rhs_weap_ak74m_camo_1p63, rhs_weap_ak74m_camo);
    RIFLE(rhs_weap_ak74m_camo_pso1m2, rhs_weap_ak74m_camo);
    RIFLE(rhs_weap_ak74m_camo_1p29, rhs_weap_ak74m_camo);
    RIFLE(rhs_weap_ak74m_desert_dtk, rhs_weap_ak74m_desert);
    RIFLE(rhs_weap_ak74m_plummag_dtk, rhs_weap_ak74m_plummag);
    RIFLE(rhs_weap_ak74m_fullplum_dtk, rhs_weap_ak74m_fullplum);
    PROTO(rhs_weap_ak74m_fullplum_npz);
    RIFLE(rhs_weap_ak74m_fullplum_npz_dtk, rhs_weap_ak74m_fullplum_npz);
    PROTO(rhs_weap_ak74m_fullplum_gp25);
    RIFLE(rhs_weap_ak74m_fullplum_gp25_dtk, rhs_weap_ak74m_fullplum_gp25);
    PROTO(rhs_weap_ak74m_fullplum_gp25_npz);
    RIFLE(rhs_weap_ak74m_fullplum_gp25_npz_dtk, rhs_weap_ak74m_fullplum_gp25_npz);
    RIFLE(rhs_weap_ak74m_gp25_dtk, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_ak74m_gp25_npz_dtk, rhs_weap_ak74m_gp25_npz);
    RIFLE(rhs_weap_ak74m_gp25_pkas, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_ak74m_gp25_1p63, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_ak74m_gp25_pso1m2, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_ak74m_gp25_1p29, rhs_weap_ak74m_gp25);
    RIFLE(rhs_weap_svdp_pso1, rhs_weap_svdp);
    RIFLE(rhs_weap_svds_pso1, rhs_weap_svds);
    PROTO(rhs_weap_m4_Base);
    RIFLE(rhs_weap_m4, rhs_weap_m4_Base);
    RIFLE(rhs_weap_m4_m320, rhs_weap_m4);
    RIFLE(rhs_weap_m4_m203, rhs_weap_m4_m320);
    RIFLE(rhs_weap_m4_grip, rhs_weap_m4);
    RIFLE(rhs_weap_m4_grip2, rhs_weap_m4_grip);
    RIFLE(rhs_weap_m4_grip3, rhs_weap_m4_grip);
    RIFLE(rhs_weap_m4_bipod, rhs_weap_m4);
    RIFLE(rhs_weap_m4_carryhandle, rhs_weap_m4);
    RIFLE(rhs_weap_m4_carryhandle_pmag, rhs_weap_m4_carryhandle);
    RIFLE(rhs_weap_m4a1, rhs_weap_m4_Base);
    RIFLE(rhs_weap_m4a1_m320, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_m203, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_carryhandle_m203, rhs_weap_m4a1_m203);
    RIFLE(rhs_weap_m4a1_grip, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_grip2, rhs_weap_m4a1_grip);
    RIFLE(rhs_weap_m4a1_grip3, rhs_weap_m4a1_grip);
    RIFLE(rhs_weap_m4a1_bipod, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_carryhandle, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_carryhandle_grip, rhs_weap_m4a1_carryhandle);
    RIFLE(rhs_weap_m4a1_carryhandle_grip2, rhs_weap_m4a1_carryhandle_grip);
    RIFLE(rhs_weap_m4a1_carryhandle_grip3, rhs_weap_m4a1_carryhandle_grip);
    RIFLE(rhs_weap_m4a1_carryhandle_bipod, rhs_weap_m4a1_carryhandle);
    RIFLE(rhs_weap_m4a1_d, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_d_grip, rhs_weap_m4a1_d);
    RIFLE(rhs_weap_m4a1_d_grip2, rhs_weap_m4a1_d_grip);
    RIFLE(rhs_weap_m4a1_d_grip3, rhs_weap_m4a1_d_grip);
    RIFLE(rhs_weap_m4a1_d_mstock, rhs_weap_m4a1_d);
    RIFLE(rhs_weap_m4a1_d_mstock_grip, rhs_weap_m4a1_d_mstock);
    RIFLE(rhs_weap_m4a1_d_mstock_grip2, rhs_weap_m4a1_d_mstock_grip);
    RIFLE(rhs_weap_m4a1_d_mstock_grip3, rhs_weap_m4a1_d_mstock_grip);
    RIFLE(rhs_weap_m4a1_wd, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_wd_grip, rhs_weap_m4a1_wd);
    RIFLE(rhs_weap_m4a1_wd_grip2, rhs_weap_m4a1_wd_grip);
    RIFLE(rhs_weap_m4a1_wd_grip3, rhs_weap_m4a1_wd_grip);
    RIFLE(rhs_weap_m4a1_wd_mstock, rhs_weap_m4a1_wd);
    RIFLE(rhs_weap_m4a1_wd_mstock_grip, rhs_weap_m4a1_wd_mstock);
    RIFLE(rhs_weap_m4a1_wd_mstock_grip2, rhs_weap_m4a1_wd_mstock_grip);
    RIFLE(rhs_weap_m4a1_wd_mstock_grip3, rhs_weap_m4a1_wd_mstock_grip);
    PROTO(rhs_weap_m4a1_m203s);
    RIFLE(rhs_weap_m4a1_m203s_wd, rhs_weap_m4a1_m203s);
    RIFLE(rhs_weap_m4a1_m203s_d, rhs_weap_m4a1_m203s);
    RIFLE(rhs_weap_m16a4, rhs_weap_m4_Base);
    RIFLE(rhs_weap_m16a4_grip, rhs_weap_m16a4);
    RIFLE(rhs_weap_m16a4_grip2, rhs_weap_m16a4_grip);
    RIFLE(rhs_weap_m16a4_bipod, rhs_weap_m16a4);
    RIFLE(rhs_weap_m16a4_carryhandle, rhs_weap_m16a4);
    RIFLE(rhs_weap_m16a4_carryhandle_M203, rhs_weap_m16a4);
    RIFLE(rhs_weap_m16a4_carryhandle_pmag, rhs_weap_m16a4_carryhandle);
    RIFLE(rhs_weap_m16a4_carryhandle_grip, rhs_weap_m16a4_carryhandle);
    RIFLE(rhs_weap_m16a4_carryhandle_grip2, rhs_weap_m16a4_carryhandle_grip);
    RIFLE(rhs_weap_m16a4_carryhandle_grip_pmag, rhs_weap_m16a4_carryhandle_pmag);
    RIFLE(rhs_weap_m16a4_carryhandle_grip2_pmag, rhs_weap_m16a4_carryhandle_grip_pmag);
    RIFLE(rhs_weap_m16a4_carryhandle_bipod, rhs_weap_m16a4_carryhandle);
    RIFLE(rhs_weap_hk416d10, rhs_weap_m4a1);
    RIFLE(rhs_weap_hk416d10_grip, rhs_weap_hk416d10);
    RIFLE(rhs_weap_hk416d10_grip2, rhs_weap_hk416d10_grip);
    RIFLE(rhs_weap_hk416d10_grip3, rhs_weap_hk416d10_grip2);
    RIFLE(rhs_weap_hk416d10_LMT, rhs_weap_hk416d10);
    RIFLE(rhs_weap_hk416d10_LMT_grip, rhs_weap_hk416d10_LMT);
    RIFLE(rhs_weap_hk416d10_LMT_grip2, rhs_weap_hk416d10_LMT_grip);
    RIFLE(rhs_weap_hk416d10_LMT_grip3, rhs_weap_hk416d10_LMT_grip2);
    RIFLE(rhs_weap_hk416d145, rhs_weap_hk416d10);
    RIFLE(rhs_weap_hk416d145_grip, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d145_grip2, rhs_weap_hk416d145_grip);
    RIFLE(rhs_weap_hk416d145_grip3, rhs_weap_hk416d145_grip2);
    RIFLE(rhs_weap_hk416d10_m320, rhs_weap_hk416d10);
    RIFLE(rhs_weap_hk416d145_m320, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d10_LMT_d, rhs_weap_hk416d10_LMT);
    RIFLE(rhs_weap_hk416d10_LMT_d_grip, rhs_weap_hk416d10_LMT_d);
    RIFLE(rhs_weap_hk416d10_LMT_d_grip2, rhs_weap_hk416d10_LMT_d_grip);
    RIFLE(rhs_weap_hk416d10_LMT_d_grip3, rhs_weap_hk416d10_LMT_d_grip2);
    RIFLE(rhs_weap_hk416d10_LMT_wd, rhs_weap_hk416d10_LMT);
    RIFLE(rhs_weap_hk416d10_LMT_wd_grip, rhs_weap_hk416d10_LMT_wd);
    RIFLE(rhs_weap_hk416d10_LMT_wd_grip2, rhs_weap_hk416d10_LMT_wd_grip);
    RIFLE(rhs_weap_hk416d10_LMT_wd_grip3, rhs_weap_hk416d10_LMT_wd_grip2);
    RIFLE(rhs_weap_hk416d145_d, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d145_d_grip, rhs_weap_hk416d145_d);
    RIFLE(rhs_weap_hk416d145_d_grip2, rhs_weap_hk416d145_d_grip);
    RIFLE(rhs_weap_hk416d145_d_grip3, rhs_weap_hk416d145_d_grip2);
    RIFLE(rhs_weap_hk416d145_d_2, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d145_d_2_grip, rhs_weap_hk416d145_d_2);
    RIFLE(rhs_weap_hk416d145_d_2_grip2, rhs_weap_hk416d145_d_2_grip);
    RIFLE(rhs_weap_hk416d145_d_2_grip3, rhs_weap_hk416d145_d_2_grip2);
    RIFLE(rhs_weap_hk416d145_wd, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d145_wd_grip, rhs_weap_hk416d145_wd);
    RIFLE(rhs_weap_hk416d145_wd_grip2, rhs_weap_hk416d145_wd_grip);
    RIFLE(rhs_weap_hk416d145_wd_grip3, rhs_weap_hk416d145_wd_grip2);
    RIFLE(rhs_weap_hk416d145_wd_2, rhs_weap_hk416d145);
    RIFLE(rhs_weap_hk416d145_wd_2_grip, rhs_weap_hk416d145_wd_2);
    RIFLE(rhs_weap_hk416d145_wd_2_grip2, rhs_weap_hk416d145_wd_2_grip);
    RIFLE(rhs_weap_hk416d145_wd_2_grip3, rhs_weap_hk416d145_wd_2_grip2);
    RIFLE(rhs_weap_m4a1_blockII, rhs_weap_m4a1);
    RIFLE(rhs_weap_m4a1_blockII_bk, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_m4a1_blockII_KAC, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_m4a1_blockII_KAC_bk, rhs_weap_m4a1_blockII_KAC);
    RIFLE(rhs_weap_m4a1_blockII_M203, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_m4a1_blockII_M203_bk, rhs_weap_m4a1_blockII_M203);
    RIFLE(rhs_weap_m4a1_blockII_wd, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_m4a1_blockII_grip_wd, rhs_weap_m4a1_blockII_wd);
    RIFLE(rhs_weap_m4a1_blockII_grip2_wd, rhs_weap_m4a1_blockII_grip_wd);
    RIFLE(rhs_weap_m4a1_blockII_d, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_m4a1_blockII_grip_d, rhs_weap_m4a1_blockII_d);
    RIFLE(rhs_weap_m4a1_blockII_grip2_d, rhs_weap_m4a1_blockII_grip_d);
    RIFLE(rhs_weap_mk18, rhs_weap_m4a1_blockII);
    RIFLE(rhs_weap_mk18_KAC, rhs_weap_mk18);
    RIFLE(rhs_weap_mk18_m320, rhs_weap_mk18);
    RIFLE(rhs_weap_mk18_bk, rhs_weap_mk18);
    RIFLE(rhs_weap_mk18_KAC_bk, rhs_weap_mk18_KAC);
    RIFLE(rhs_weap_mk18_wd, rhs_weap_mk18);
    RIFLE(rhs_weap_mk18_KAC_wd, rhs_weap_mk18_KAC);
    RIFLE(rhs_weap_mk18_d, rhs_weap_mk18);
    RIFLE(rhs_weap_mk18_KAC_d, rhs_weap_mk18_KAC);
    RIFLE(rhs_weap_m27iar, rhs_weap_m4a1);
    RIFLE(rhs_weap_m27iar_grip, rhs_weap_m27iar);
    RIFLE(rhs_weap_m27iar_grip2, rhs_weap_m27iar);
    RIFLE(rhs_weap_m27iar_grip3, rhs_weap_m27iar_grip2);
    PROTO(rhs_weap_lmg_minimi_railed);
    RIFLE(rhs_weap_m249_pip_S, rhs_weap_lmg_minimi_railed);
    RIFLE(rhs_weap_m249_pip_S_para, rhs_weap_m249_pip_S);
    RIFLE(rhs_weap_m249_pip_S_vfg, rhs_weap_m249_pip_S);
    RIFLE(rhs_weap_m249_pip_L, rhs_weap_lmg_minimi_railed);
    RIFLE(rhs_weap_m249_pip_L_para, rhs_weap_m249_pip_L);
    RIFLE(rhs_weap_m249_pip_L_vfg, rhs_weap_m249_pip_L);
    PROTO(rhs_weap_m240_base);
    MG(rhs_weap_m240B, rhs_weap_m240_base);
    MG(rhs_weap_m240B_CAP, rhs_weap_m240B);
    MG(rhs_weap_m240G, rhs_weap_m240_base);
    RIFLE(rhs_weap_m14ebrri, srifle_EBR_F);
    RIFLE(rhs_weap_sr25, rhs_weap_m14ebrri);
    RIFLE(rhs_weap_sr25_ec, rhs_weap_sr25);
    RIFLE(rhs_weap_m39, rhs_weap_m14ebrri);
    PROTO(rhs_weap_XM2010_Base_F);
    RIFLE(rhs_weap_XM2010, rhs_weap_XM2010_Base_F);
    RIFLE(rhs_weap_XM2010_d, rhs_weap_XM2010);
    RIFLE(rhs_weap_XM2010_wd, rhs_weap_XM2010);
    RIFLE(rhs_weap_XM2010_sa, rhs_weap_XM2010);
    PROTO(rhs_weap_m32_Base_F);
    RIFLE(rhs_weap_m32, rhs_weap_m32_Base_F);
    PROTO(rhs_weap_M107_Base_F);
    RIFLE(rhs_weap_M107, rhs_weap_M107_Base_F);
    PROTO(Rifle_Base_F);
    RIFLE(rhs_weap_M590_5RD, Rifle_Base_F);
    RIFLE(rhs_weap_M590_8RD, rhs_weap_M590_5RD);
    RIFLE(rhs_m4_compm4, rhs_weap_m4_carryhandle);
    RIFLE(rhs_m4_acog, rhs_weap_m4_carryhandle);
    PROTO(rhs_weap_m4_carryhandle_grip3);
    RIFLE(rhs_m4_grip_compm4, rhs_weap_m4_carryhandle_grip3);
    RIFLE(arifle_MX_GL_khk_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_GL_khk_ACO_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Hamr_Pointer_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Holo_Pointer_Snds_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_khk_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Holo_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_SW_khk_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MX_SW_khk_Pointer_F, arifle_MX_SW_khk_F);
    RIFLE(arifle_MXC_khk_F, arifle_MXC_Black_F);
    RIFLE(arifle_MXC_khk_ACO_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_ACO_Pointer_Snds_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_Holo_Pointer_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXM_khk_F, arifle_MXM_Black_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_F, arifle_MXM_khk_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F, arifle_MXM_khk_F);
    RIFLE(srifle_GM6_ghex_F, srifle_GM6_F);
    RIFLE(srifle_GM6_ghex_LRPS_F, srifle_GM6_ghex_F);
    RIFLE(srifle_LRR_tna_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_tna_LRPS_F, srifle_LRR_tna_F);
    PROTO(DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_DMS_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_blk_DMS_Snds_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_ghex_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_hex_F, DMR_07_base_F);
    PROTO(LMG_03_base_F);
    MG(LMG_03_F, LMG_03_base_F);
    PROTO(arifle_AK12_base_F);
    RIFLE(arifle_AK12_F, arifle_AK12_base_F);
    PROTO(arifle_AK12_GL_base_F);
    RIFLE(arifle_AK12_GL_F, arifle_AK12_GL_base_F);
    PROTO(arifle_AKM_base_F);
    RIFLE(arifle_AKM_F, arifle_AKM_base_F);
    PROTO(arifle_AKS_base_F);
    RIFLE(arifle_AKS_F, arifle_AKS_base_F);
    PROTO(arifle_ARX_base_F);
    RIFLE(arifle_ARX_blk_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_ghex_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_hex_F, arifle_ARX_base_F);
    PROTO(arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_F, arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_ACO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_ghex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_Pointer_Snds_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ARCO_Pointer_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_ghex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_hex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_hex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_Pointer_F, arifle_CTARS_blk_F);
    MG(arifle_CTARS_ghex_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_hex_F, arifle_CTARS_base_F);
    PROTO(arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_blk_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_blk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_khk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_snd_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_khk_F, arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_snd_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_blk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_khk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_snd_F, arifle_SPAR_02_base_F);
    PROTO(arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_blk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_khk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_snd_F, arifle_SPAR_03_base_F);
    PROTO(SMG_05_base_F);
    RIFLE(SMG_05_F, SMG_05_base_F);
    RIFLE(B_Patrol_Soldier_Autorifleman_weapon_F, arifle_MX_SW_F);
    RIFLE(B_Patrol_Soldier_Carrier_weapon_F, arifle_MX_F);
    MG(B_Patrol_Soldier_HeavyGunner_weapon_F, LMG_Zafir_F);
    RIFLE(B_Patrol_Soldier_Leader_weapon_F, arifle_MX_GL_F);
    MG(B_Patrol_Soldier_MachineGunner_weapon_F, LMG_Mk200_F);
    RIFLE(B_Patrol_Soldier_Marksman_weapon_F, srifle_EBR_F);
    RIFLE(B_Patrol_Soldier_Medic_weapon_F, arifle_MX_F);
    RIFLE(B_Patrol_Soldier_Operator_weapon_F, arifle_MXC_F);
    RIFLE(B_Patrol_Soldier_Specialist_weapon_F, arifle_MX_F);
};
