class CfgAmmo {
    PROTO(Grenade);
    GRENADE(GrenadeHand, Grenade);
    GRENADE(mini_Grenade, GrenadeHand);
    GRENADE(SmokeShell, GrenadeHand);
    GRENADE(SmokeShellRed, SmokeShell);
    GRENADE(SmokeShellGreen, SmokeShell);
    GRENADE(SmokeShellYellow, SmokeShell);
    GRENADE(SmokeShellPurple, SmokeShell);
    GRENADE(SmokeShellBlue, SmokeShell);
    GRENADE(SmokeShellOrange, SmokeShell);
    PROTO(Chemlight_base);
    GRENADE(Chemlight_green, Chemlight_base);
    GRENADE(Chemlight_red, Chemlight_base);
    GRENADE(Chemlight_yellow, Chemlight_base);
    GRENADE(Chemlight_blue, Chemlight_base);
    GRENADE(ACE_G_Handflare_White, SmokeShell);
    GRENADE(ACE_G_Handflare_Red, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Green, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Yellow, ACE_G_Handflare_White);
    GRENADE(ACE_G_M84, SmokeShell);
    GRENADE(ACE_G_M14, SmokeShell);
    GRENADE(ACE_G_Chemlight_Orange, Chemlight_base);
    GRENADE(ACE_G_Chemlight_White, Chemlight_base);
    GRENADE(ACE_G_Chemlight_HiRed, Chemlight_red);
    GRENADE(ACE_G_Chemlight_HiYellow, Chemlight_yellow);
    GRENADE(ACE_G_Chemlight_HiOrange, ACE_G_Chemlight_Orange);
    GRENADE(ACE_G_Chemlight_HiWhite, ACE_G_Chemlight_White);
    GRENADE(ACE_G_Chemlight_IR, Chemlight_base);
};

class CfgWeapons {
    PROTO(DMR_01_base_F);
    RIFLE(srifle_DMR_01_F, DMR_01_base_F);
    RIFLE(srifle_DMR_01_ACO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_ARCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_snds_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_MRCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_SOS_F, srifle_DMR_01_F);
    PROTO(EBR_base_F);
    RIFLE(srifle_EBR_F, EBR_base_F);
    RIFLE(srifle_EBR_ACO_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_Hamr_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_MRCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_SOS_F, srifle_EBR_F);
    PROTO(GM6_base_F);
    RIFLE(srifle_GM6_F, GM6_base_F);
    RIFLE(srifle_GM6_camo_F, srifle_GM6_F);
    RIFLE(srifle_GM6_camo_LRPS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_camo_SOS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_LRPS_F, srifle_GM6_F);
    RIFLE(srifle_GM6_SOS_F, srifle_GM6_F);
    PROTO(LRR_base_F);
    RIFLE(srifle_LRR_F, LRR_base_F);
    RIFLE(srifle_LRR_camo_F, srifle_LRR_F);
    RIFLE(srifle_LRR_camo_LRPS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_camo_SOS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_LRPS_F, srifle_LRR_F);
    RIFLE(srifle_LRR_SOS_F, srifle_LRR_F);
    PROTO(Rifle_Long_Base_F);
    MG(LMG_Mk200_F, Rifle_Long_Base_F);
    MG(LMG_Mk200_MRCO_F, LMG_Mk200_F);
    MG(LMG_Mk200_pointer_F, LMG_Mk200_F);
    MG(LMG_Zafir_F, Rifle_Long_Base_F);
    MG(LMG_Zafir_ARCO_F, LMG_Zafir_F);
    MG(LMG_Zafir_pointer_F, LMG_Zafir_F);
    PROTO(arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_ACO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_C_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_C_ACO_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_snds_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_GL_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_GL_ACO_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_snds_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ARCO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_Nstalker_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_pointer_F, arifle_Katiba_F);
    PROTO(mk20_base_F);
    RIFLE(arifle_Mk20_F, mk20_base_F);
    RIFLE(arifle_Mk20_ACO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_ACO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_GL_F, mk20_base_F);
    RIFLE(arifle_Mk20_GL_ACO_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_MRCO_pointer_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_plain_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_Holo_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_plain_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_plain_F, arifle_Mk20_plain_F);
    RIFLE(arifle_Mk20_MRCO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20C_F, mk20_base_F);
    RIFLE(arifle_Mk20C_ACO_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_ACO_pointer_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_plain_F, arifle_Mk20C_F);
    PROTO(arifle_MX_Base_F);
    RIFLE(arifle_MX_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_ACO_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_GL_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_GL_ACO_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_ACO_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Hamr_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Holo_pointer_snds_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_Hamr_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_Holo_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_RCO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_SW_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_SW_Hamr_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MXC_F, arifle_MX_Base_F);
    RIFLE(arifle_MXC_ACO_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_SOS_point_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXM_F, arifle_MX_Base_F);
    RIFLE(arifle_MXM_DMS_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MXM_RCO_pointer_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_SOS_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MX_Black_F, arifle_MX_F);
    RIFLE(arifle_MX_Black_Hamr_pointer_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_GL_Black_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Black_Hamr_pointer_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_SW_Black_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_Black_Hamr_pointer_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MXC_Black_F, arifle_MXC_F);
    RIFLE(arifle_MXM_Black_F, arifle_MXM_F);
    PROTO(SDAR_base_F);
    RIFLE(arifle_SDAR_F, SDAR_base_F);
    PROTO(Tavor_base_F);
    RIFLE(arifle_TRG20_F, Tavor_base_F);
    RIFLE(arifle_TRG20_ACO_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_Flash_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_pointer_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_Holo_F, arifle_TRG20_F);
    RIFLE(arifle_TRG21_F, Tavor_base_F);
    RIFLE(arifle_TRG21_ACO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_ARCO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_ACO_pointer_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_GL_MRCO_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_MRCO_F, arifle_TRG21_F);
    PROTO(pdw2000_base_F);
    RIFLE(hgun_PDW2000_F, pdw2000_base_F);
    RIFLE(hgun_PDW2000_Holo_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_Holo_snds_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_snds_F, hgun_PDW2000_F);
    PROTO(SMG_01_Base);
    RIFLE(SMG_01_F, SMG_01_Base);
    RIFLE(SMG_01_ACO_F, SMG_01_F);
    RIFLE(SMG_01_Holo_F, SMG_01_F);
    RIFLE(SMG_01_Holo_pointer_snds_F, SMG_01_F);
    PROTO(SMG_02_base_F);
    RIFLE(SMG_02_F, SMG_02_base_F);
    RIFLE(SMG_02_ACO_F, SMG_02_F);
    RIFLE(SMG_02_ARCO_pointg_F, SMG_02_F);
    RIFLE(srifle_DMR_01_DMS_BI_F, srifle_DMR_01_DMS_F);
    RIFLE(srifle_DMR_01_DMS_snds_BI_F, srifle_DMR_01_DMS_snds_F);
    PROTO(DMR_02_base_F);
    RIFLE(srifle_DMR_02_F, DMR_02_base_F);
    RIFLE(srifle_DMR_02_ACO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_ARCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_AMS_LP_F, srifle_DMR_02_camo_F);
    RIFLE(srifle_DMR_02_DMS_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_MRCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_AMS_LP_S_F, srifle_DMR_02_sniper_F);
    RIFLE(srifle_DMR_02_SOS_F, srifle_DMR_02_F);
    PROTO(DMR_03_base_F);
    RIFLE(srifle_DMR_03_F, DMR_03_base_F);
    RIFLE(srifle_DMR_03_ACO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_AMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_ARCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_snds_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_khaki_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_MRCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_multicam_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_SOS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_AMS_LP_F, srifle_DMR_03_tan_F);
    RIFLE(srifle_DMR_03_woodland_F, srifle_DMR_03_F);
    PROTO(DMR_04_base_F);
    RIFLE(srifle_DMR_04_F, DMR_04_base_F);
    RIFLE(srifle_DMR_04_ACO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_ARCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_DMS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_MRCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_NS_LP_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_SOS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_Tan_F, srifle_DMR_04_F);
    PROTO(DMR_05_base_F);
    RIFLE(srifle_DMR_05_blk_F, DMR_05_base_F);
    RIFLE(srifle_DMR_05_ACO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_ARCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_snds_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_hex_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_KHS_LP_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_MRCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_SOS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_tan_f, srifle_DMR_05_blk_F);
    PROTO(DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_F, DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_khs_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_DMR_06_olive_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_EBR_MRCO_LP_BI_F, srifle_EBR_F);
    MG(LMG_Mk200_BI_F, LMG_Mk200_F);
    MG(LMG_Mk200_LP_BI_F, LMG_Mk200_pointer_F);
    PROTO(MMG_01_base_F);
    MG(MMG_01_hex_F, MMG_01_base_F);
    MG(MMG_01_hex_ARCO_LP_F, MMG_01_hex_F);
    MG(MMG_01_tan_F, MMG_01_hex_F);
    PROTO(MMG_02_base_F);
    MG(MMG_02_camo_F, MMG_02_base_F);
    MG(MMG_02_black_F, MMG_02_camo_F);
    MG(MMG_02_black_RCO_BI_F, MMG_02_black_F);
    MG(MMG_02_sand_F, MMG_02_camo_F);
    MG(MMG_02_sand_RCO_LP_F, MMG_02_sand_F);
    RIFLE(arifle_MXM_DMS_LP_BI_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_LP_BI_F, arifle_MXM_Hamr_pointer_F);
    RIFLE(arifle_MX_GL_khk_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_GL_khk_ACO_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Hamr_Pointer_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Holo_Pointer_Snds_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_khk_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Holo_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_SW_khk_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MX_SW_khk_Pointer_F, arifle_MX_SW_khk_F);
    RIFLE(arifle_MXC_khk_F, arifle_MXC_Black_F);
    RIFLE(arifle_MXC_khk_ACO_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_ACO_Pointer_Snds_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_Holo_Pointer_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXM_khk_F, arifle_MXM_Black_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_F, arifle_MXM_khk_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F, arifle_MXM_khk_F);
    RIFLE(srifle_GM6_ghex_F, srifle_GM6_F);
    RIFLE(srifle_GM6_ghex_LRPS_F, srifle_GM6_ghex_F);
    RIFLE(srifle_LRR_tna_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_tna_LRPS_F, srifle_LRR_tna_F);
    PROTO(DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_DMS_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_blk_DMS_Snds_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_ghex_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_hex_F, DMR_07_base_F);
    PROTO(LMG_03_base_F);
    MG(LMG_03_F, LMG_03_base_F);
    MG(LMG_03_Vehicle_F, LMG_03_F);
    PROTO(arifle_AK12_base_F);
    RIFLE(arifle_AK12_F, arifle_AK12_base_F);
    PROTO(arifle_AK12_GL_base_F);
    RIFLE(arifle_AK12_GL_F, arifle_AK12_GL_base_F);
    PROTO(arifle_AKM_base_F);
    RIFLE(arifle_AKM_F, arifle_AKM_base_F);
    PROTO(arifle_AKS_base_F);
    RIFLE(arifle_AKS_F, arifle_AKS_base_F);
    PROTO(arifle_ARX_base_F);
    RIFLE(arifle_ARX_blk_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_ghex_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_hex_F, arifle_ARX_base_F);
    PROTO(arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_F, arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_ACO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_ghex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_Pointer_Snds_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ARCO_Pointer_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_ghex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_hex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_hex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_Pointer_F, arifle_CTARS_blk_F);
    MG(arifle_CTARS_ghex_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_hex_F, arifle_CTARS_base_F);
    PROTO(arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_blk_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_blk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_khk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_snd_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_khk_F, arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_snd_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_blk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_khk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_snd_F, arifle_SPAR_02_base_F);
    PROTO(arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_blk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_khk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_snd_F, arifle_SPAR_03_base_F);
    PROTO(SMG_05_base_F);
    RIFLE(SMG_05_F, SMG_05_base_F);
    RIFLE(B_Patrol_Soldier_Autorifleman_weapon_F, arifle_MX_SW_F);
    RIFLE(B_Patrol_Soldier_Carrier_weapon_F, arifle_MX_F);
    MG(B_Patrol_Soldier_HeavyGunner_weapon_F, LMG_Zafir_F);
    RIFLE(B_Patrol_Soldier_Leader_weapon_F, arifle_MX_GL_F);
    MG(B_Patrol_Soldier_MachineGunner_weapon_F, LMG_Mk200_F);
    RIFLE(B_Patrol_Soldier_Marksman_weapon_F, srifle_EBR_F);
    RIFLE(B_Patrol_Soldier_Medic_weapon_F, arifle_MX_F);
    RIFLE(B_Patrol_Soldier_Operator_weapon_F, arifle_MXC_F);
    RIFLE(B_Patrol_Soldier_Specialist_weapon_F, arifle_MX_F);
    RIFLE(arifle_CTAR_blk_aco_flash_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_arco_flash_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_flash_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_GL_blk_aco_flash_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_arco_flash_F, arifle_CTAR_GL_blk_F);
    MG(arifle_CTARS_blk_flash_F, arifle_CTARS_blk_F);
    RIFLE(SMG_02_flash_F, SMG_02_F);
    RIFLE(srifle_DMR_07_blk_F_arco_flash_F, srifle_DMR_07_blk_F);
};
