class CfgAmmo {
    PROTO(Grenade);
    GRENADE(GrenadeHand, Grenade);
    GRENADE(mini_Grenade, GrenadeHand);
    GRENADE(SmokeShell, GrenadeHand);
    GRENADE(SmokeShellRed, SmokeShell);
    GRENADE(SmokeShellGreen, SmokeShell);
    GRENADE(SmokeShellYellow, SmokeShell);
    GRENADE(SmokeShellPurple, SmokeShell);
    GRENADE(SmokeShellBlue, SmokeShell);
    GRENADE(SmokeShellOrange, SmokeShell);
    PROTO(Chemlight_base);
    GRENADE(Chemlight_green, Chemlight_base);
    GRENADE(Chemlight_red, Chemlight_base);
    GRENADE(Chemlight_yellow, Chemlight_base);
    GRENADE(Chemlight_blue, Chemlight_base);
    GRENADE(CUP_GrenadeHand_M67, GrenadeHand);
    GRENADE(CUP_GrenadeHand_L109A1_HE, GrenadeHand);
    GRENADE(CUP_GrenadeHand_L109A2_HE, GrenadeHand);
    GRENADE(CUP_GrenadeHand_RGD5, GrenadeHand);
    GRENADE(ACE_G_Handflare_White, SmokeShell);
    GRENADE(ACE_G_Handflare_Red, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Green, ACE_G_Handflare_White);
    GRENADE(ACE_G_Handflare_Yellow, ACE_G_Handflare_White);
    GRENADE(ACE_G_M84, SmokeShell);
    GRENADE(ACE_G_M14, SmokeShell);
    GRENADE(ACE_G_Chemlight_Orange, Chemlight_base);
    GRENADE(ACE_G_Chemlight_White, Chemlight_base);
    GRENADE(ACE_G_Chemlight_HiRed, Chemlight_red);
    GRENADE(ACE_G_Chemlight_HiYellow, Chemlight_yellow);
    GRENADE(ACE_G_Chemlight_HiOrange, ACE_G_Chemlight_Orange);
    GRENADE(ACE_G_Chemlight_HiWhite, ACE_G_Chemlight_White);
    GRENADE(ACE_G_Chemlight_IR, Chemlight_base);
};

class CfgWeapons {
    PROTO(DMR_01_base_F);
    RIFLE(srifle_DMR_01_F, DMR_01_base_F);
    RIFLE(srifle_DMR_01_ACO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_ARCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_DMS_snds_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_MRCO_F, srifle_DMR_01_F);
    RIFLE(srifle_DMR_01_SOS_F, srifle_DMR_01_F);
    PROTO(EBR_base_F);
    RIFLE(srifle_EBR_F, EBR_base_F);
    RIFLE(srifle_EBR_ACO_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_ARCO_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_F, srifle_EBR_F);
    RIFLE(srifle_EBR_DMS_pointer_snds_F, srifle_EBR_F);
    RIFLE(srifle_EBR_Hamr_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_MRCO_pointer_F, srifle_EBR_F);
    RIFLE(srifle_EBR_SOS_F, srifle_EBR_F);
    PROTO(GM6_base_F);
    RIFLE(srifle_GM6_F, GM6_base_F);
    RIFLE(srifle_GM6_camo_F, srifle_GM6_F);
    RIFLE(srifle_GM6_camo_LRPS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_camo_SOS_F, srifle_GM6_camo_F);
    RIFLE(srifle_GM6_LRPS_F, srifle_GM6_F);
    RIFLE(srifle_GM6_SOS_F, srifle_GM6_F);
    PROTO(LRR_base_F);
    RIFLE(srifle_LRR_F, LRR_base_F);
    RIFLE(srifle_LRR_camo_F, srifle_LRR_F);
    RIFLE(srifle_LRR_camo_LRPS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_camo_SOS_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_LRPS_F, srifle_LRR_F);
    RIFLE(srifle_LRR_SOS_F, srifle_LRR_F);
    PROTO(Rifle_Long_Base_F);
    MG(LMG_Mk200_F, Rifle_Long_Base_F);
    MG(LMG_Mk200_MRCO_F, LMG_Mk200_F);
    MG(LMG_Mk200_pointer_F, LMG_Mk200_F);
    MG(LMG_Zafir_F, Rifle_Long_Base_F);
    MG(LMG_Zafir_ARCO_F, LMG_Zafir_F);
    MG(LMG_Zafir_pointer_F, LMG_Zafir_F);
    PROTO(arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_ACO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ACO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_ARCO_pointer_snds_F, arifle_Katiba_F);
    RIFLE(arifle_Katiba_C_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_C_ACO_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_C_ACO_pointer_snds_F, arifle_Katiba_C_F);
    RIFLE(arifle_Katiba_GL_F, arifle_Katiba_Base_F);
    RIFLE(arifle_Katiba_GL_ACO_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ACO_pointer_snds_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_ARCO_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_GL_Nstalker_pointer_F, arifle_Katiba_GL_F);
    RIFLE(arifle_Katiba_pointer_F, arifle_Katiba_F);
    PROTO(mk20_base_F);
    RIFLE(arifle_Mk20_F, mk20_base_F);
    RIFLE(arifle_Mk20_ACO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_ACO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_GL_F, mk20_base_F);
    RIFLE(arifle_Mk20_GL_ACO_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_MRCO_pointer_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_GL_plain_F, arifle_Mk20_GL_F);
    RIFLE(arifle_Mk20_Holo_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_plain_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_MRCO_plain_F, arifle_Mk20_plain_F);
    RIFLE(arifle_Mk20_MRCO_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20_pointer_F, arifle_Mk20_F);
    RIFLE(arifle_Mk20C_F, mk20_base_F);
    RIFLE(arifle_Mk20C_ACO_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_ACO_pointer_F, arifle_Mk20C_F);
    RIFLE(arifle_Mk20C_plain_F, arifle_Mk20C_F);
    PROTO(arifle_MX_Base_F);
    RIFLE(arifle_MX_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_ACO_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_ACO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_GL_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_GL_ACO_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_ACO_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Hamr_pointer_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Holo_pointer_snds_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_Hamr_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_Holo_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_pointer_F, arifle_MX_F);
    RIFLE(arifle_MX_RCO_pointer_snds_F, arifle_MX_F);
    RIFLE(arifle_MX_SW_F, arifle_MX_Base_F);
    RIFLE(arifle_MX_SW_Hamr_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_pointer_F, arifle_MX_SW_F);
    RIFLE(arifle_MXC_F, arifle_MX_Base_F);
    RIFLE(arifle_MXC_ACO_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_ACO_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_F, arifle_MXC_F);
    RIFLE(arifle_MXC_Holo_pointer_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXC_SOS_point_snds_F, arifle_MXC_F);
    RIFLE(arifle_MXM_F, arifle_MX_Base_F);
    RIFLE(arifle_MXM_DMS_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MXM_RCO_pointer_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_SOS_pointer_F, arifle_MXM_F);
    RIFLE(arifle_MX_Black_F, arifle_MX_F);
    RIFLE(arifle_MX_Black_Hamr_pointer_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_GL_Black_F, arifle_MX_GL_F);
    RIFLE(arifle_MX_GL_Black_Hamr_pointer_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_SW_Black_F, arifle_MX_SW_F);
    RIFLE(arifle_MX_SW_Black_Hamr_pointer_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MXC_Black_F, arifle_MXC_F);
    RIFLE(arifle_MXM_Black_F, arifle_MXM_F);
    PROTO(SDAR_base_F);
    RIFLE(arifle_SDAR_F, SDAR_base_F);
    PROTO(Tavor_base_F);
    RIFLE(arifle_TRG20_F, Tavor_base_F);
    RIFLE(arifle_TRG20_ACO_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_Flash_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_ACO_pointer_F, arifle_TRG20_F);
    RIFLE(arifle_TRG20_Holo_F, arifle_TRG20_F);
    RIFLE(arifle_TRG21_F, Tavor_base_F);
    RIFLE(arifle_TRG21_ACO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_ARCO_pointer_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_F, arifle_TRG21_F);
    RIFLE(arifle_TRG21_GL_ACO_pointer_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_GL_MRCO_F, arifle_TRG21_GL_F);
    RIFLE(arifle_TRG21_MRCO_F, arifle_TRG21_F);
    PROTO(pdw2000_base_F);
    RIFLE(hgun_PDW2000_F, pdw2000_base_F);
    RIFLE(hgun_PDW2000_Holo_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_Holo_snds_F, hgun_PDW2000_F);
    RIFLE(hgun_PDW2000_snds_F, hgun_PDW2000_F);
    PROTO(SMG_01_Base);
    RIFLE(SMG_01_F, SMG_01_Base);
    RIFLE(SMG_01_ACO_F, SMG_01_F);
    RIFLE(SMG_01_Holo_F, SMG_01_F);
    RIFLE(SMG_01_Holo_pointer_snds_F, SMG_01_F);
    PROTO(SMG_02_base_F);
    RIFLE(SMG_02_F, SMG_02_base_F);
    RIFLE(SMG_02_ACO_F, SMG_02_F);
    RIFLE(SMG_02_ARCO_pointg_F, SMG_02_F);
    PROTO(CUP_srifle_CZ750_Base);
    RIFLE(CUP_srifle_CZ750, CUP_srifle_CZ750_Base);
    RIFLE(CUP_srifle_CZ750_SOS_bipod, CUP_srifle_CZ750);
    PROTO(CUP_srifle_CZ550_base);
    RIFLE(CUP_srifle_CZ550, CUP_srifle_CZ550_base);
    RIFLE(CUP_srifle_CZ550_rail, CUP_srifle_CZ550_base);
    PROTO(Rifle_Base_F);
    RIFLE(CUP_srifle_LeeEnfield, Rifle_Base_F);
    RIFLE(CUP_srifle_LeeEnfield_rail, CUP_srifle_LeeEnfield);
    RIFLE(CUP_srifle_M24_des, Rifle_Base_F);
    RIFLE(CUP_srifle_M24_wdl, CUP_srifle_M24_des);
    RIFLE(CUP_srifle_M24_ghillie, CUP_srifle_M24_des);
    RIFLE(CUP_srifle_M40A3, CUP_srifle_M24_des);
    RIFLE(CUP_srifle_M24_des_LeupoldMk4LRT, CUP_srifle_M24_des);
    RIFLE(CUP_srifle_M24_wdl_LeupoldMk4LRT, CUP_srifle_M24_wdl);
    RIFLE(CUP_srifle_M24_ghillie_bipod, CUP_srifle_M24_ghillie);
    RIFLE(CUP_srifle_M40A3_bipod, CUP_srifle_M40A3);
    RIFLE(srifle_DMR_01_DMS_BI_F, srifle_DMR_01_DMS_F);
    RIFLE(srifle_DMR_01_DMS_snds_BI_F, srifle_DMR_01_DMS_snds_F);
    PROTO(DMR_02_base_F);
    RIFLE(srifle_DMR_02_F, DMR_02_base_F);
    RIFLE(srifle_DMR_02_ACO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_ARCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_camo_AMS_LP_F, srifle_DMR_02_camo_F);
    RIFLE(srifle_DMR_02_DMS_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_MRCO_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_F, srifle_DMR_02_F);
    RIFLE(srifle_DMR_02_sniper_AMS_LP_S_F, srifle_DMR_02_sniper_F);
    RIFLE(srifle_DMR_02_SOS_F, srifle_DMR_02_F);
    PROTO(DMR_03_base_F);
    RIFLE(srifle_DMR_03_F, DMR_03_base_F);
    RIFLE(srifle_DMR_03_ACO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_AMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_ARCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_DMS_snds_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_khaki_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_MRCO_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_multicam_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_SOS_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_F, srifle_DMR_03_F);
    RIFLE(srifle_DMR_03_tan_AMS_LP_F, srifle_DMR_03_tan_F);
    RIFLE(srifle_DMR_03_woodland_F, srifle_DMR_03_F);
    PROTO(DMR_04_base_F);
    RIFLE(srifle_DMR_04_F, DMR_04_base_F);
    RIFLE(srifle_DMR_04_ACO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_ARCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_DMS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_MRCO_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_NS_LP_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_SOS_F, srifle_DMR_04_F);
    RIFLE(srifle_DMR_04_Tan_F, srifle_DMR_04_F);
    PROTO(DMR_05_base_F);
    RIFLE(srifle_DMR_05_blk_F, DMR_05_base_F);
    RIFLE(srifle_DMR_05_ACO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_ARCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_DMS_snds_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_hex_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_KHS_LP_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_MRCO_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_SOS_F, srifle_DMR_05_blk_F);
    RIFLE(srifle_DMR_05_tan_f, srifle_DMR_05_blk_F);
    PROTO(DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_F, DMR_06_base_F);
    RIFLE(srifle_DMR_06_camo_khs_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_DMR_06_olive_F, srifle_DMR_06_camo_F);
    RIFLE(srifle_EBR_MRCO_LP_BI_F, srifle_EBR_F);
    MG(LMG_Mk200_BI_F, LMG_Mk200_F);
    MG(LMG_Mk200_LP_BI_F, LMG_Mk200_pointer_F);
    PROTO(MMG_01_base_F);
    MG(MMG_01_hex_F, MMG_01_base_F);
    MG(MMG_01_hex_ARCO_LP_F, MMG_01_hex_F);
    MG(MMG_01_tan_F, MMG_01_hex_F);
    PROTO(MMG_02_base_F);
    MG(MMG_02_camo_F, MMG_02_base_F);
    MG(MMG_02_black_F, MMG_02_camo_F);
    MG(MMG_02_black_RCO_BI_F, MMG_02_black_F);
    MG(MMG_02_sand_F, MMG_02_camo_F);
    MG(MMG_02_sand_RCO_LP_F, MMG_02_sand_F);
    RIFLE(arifle_MXM_DMS_LP_BI_snds_F, arifle_MXM_F);
    RIFLE(arifle_MXM_Hamr_LP_BI_F, arifle_MXM_Hamr_pointer_F);
    RIFLE(CUP_sgun_AA12, Rifle_Base_F);
    RIFLE(arifle_MX_GL_khk_F, arifle_MX_GL_Black_F);
    RIFLE(arifle_MX_GL_khk_ACO_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Hamr_Pointer_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_GL_khk_Holo_Pointer_Snds_F, arifle_MX_GL_khk_F);
    RIFLE(arifle_MX_khk_F, arifle_MX_Black_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_ACO_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Hamr_Pointer_Snds_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Holo_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_khk_Pointer_F, arifle_MX_khk_F);
    RIFLE(arifle_MX_SW_khk_F, arifle_MX_SW_Black_F);
    RIFLE(arifle_MX_SW_khk_Pointer_F, arifle_MX_SW_khk_F);
    RIFLE(arifle_MXC_khk_F, arifle_MXC_Black_F);
    RIFLE(arifle_MXC_khk_ACO_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_ACO_Pointer_Snds_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXC_khk_Holo_Pointer_F, arifle_MXC_khk_F);
    RIFLE(arifle_MXM_khk_F, arifle_MXM_Black_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_F, arifle_MXM_khk_F);
    RIFLE(arifle_MXM_khk_MOS_Pointer_Bipod_Snds_F, arifle_MXM_khk_F);
    RIFLE(srifle_GM6_ghex_F, srifle_GM6_F);
    RIFLE(srifle_GM6_ghex_LRPS_F, srifle_GM6_ghex_F);
    RIFLE(srifle_LRR_tna_F, srifle_LRR_camo_F);
    RIFLE(srifle_LRR_tna_LRPS_F, srifle_LRR_tna_F);
    PROTO(DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_blk_DMS_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_blk_DMS_Snds_F, srifle_DMR_07_blk_F);
    RIFLE(srifle_DMR_07_ghex_F, DMR_07_base_F);
    RIFLE(srifle_DMR_07_hex_F, DMR_07_base_F);
    PROTO(LMG_03_base_F);
    MG(LMG_03_F, LMG_03_base_F);
    PROTO(arifle_AK12_base_F);
    RIFLE(arifle_AK12_F, arifle_AK12_base_F);
    PROTO(arifle_AK12_GL_base_F);
    RIFLE(arifle_AK12_GL_F, arifle_AK12_GL_base_F);
    PROTO(arifle_AKM_base_F);
    RIFLE(arifle_AKM_F, arifle_AKM_base_F);
    PROTO(arifle_AKS_base_F);
    RIFLE(arifle_AKS_F, arifle_AKS_base_F);
    PROTO(arifle_ARX_base_F);
    RIFLE(arifle_ARX_blk_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_ghex_F, arifle_ARX_base_F);
    RIFLE(arifle_ARX_hex_F, arifle_ARX_base_F);
    PROTO(arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_F, arifle_CTAR_base_F);
    RIFLE(arifle_CTAR_blk_ACO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ACO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_ARCO_Pointer_Snds_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_blk_Pointer_F, arifle_CTAR_blk_F);
    RIFLE(arifle_CTAR_ghex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ACO_Pointer_Snds_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_blk_ARCO_Pointer_F, arifle_CTAR_GL_blk_F);
    RIFLE(arifle_CTAR_GL_ghex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_GL_hex_F, arifle_CTAR_GL_base_F);
    RIFLE(arifle_CTAR_hex_F, arifle_CTAR_base_F);
    PROTO(arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_blk_Pointer_F, arifle_CTARS_blk_F);
    MG(arifle_CTARS_ghex_F, arifle_CTARS_base_F);
    MG(arifle_CTARS_hex_F, arifle_CTARS_base_F);
    PROTO(arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_blk_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_blk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_khk_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_GL_snd_F, arifle_SPAR_01_GL_base_F);
    RIFLE(arifle_SPAR_01_khk_F, arifle_SPAR_01_base_F);
    RIFLE(arifle_SPAR_01_snd_F, arifle_SPAR_01_base_F);
    PROTO(arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_blk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_khk_F, arifle_SPAR_02_base_F);
    MG(arifle_SPAR_02_snd_F, arifle_SPAR_02_base_F);
    PROTO(arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_blk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_khk_F, arifle_SPAR_03_base_F);
    RIFLE(arifle_SPAR_03_snd_F, arifle_SPAR_03_base_F);
    PROTO(SMG_05_base_F);
    RIFLE(SMG_05_F, SMG_05_base_F);
    PROTO(CUP_glaunch_Base);
    RIFLE(CUP_glaunch_M32, CUP_glaunch_Base);
    RIFLE(CUP_glaunch_M79, CUP_glaunch_Base);
    RIFLE(CUP_glaunch_Mk13, CUP_glaunch_Base);
    RIFLE(CUP_glaunch_6G30, CUP_glaunch_M32);
    RIFLE(CUP_srifle_ksvk, Rifle_Base_F);
    RIFLE(CUP_srifle_ksvk_PSO3, CUP_srifle_ksvk);
    RIFLE(CUP_smg_MP5SD6, Rifle_Base_F);
    RIFLE(CUP_smg_MP5A5, CUP_smg_MP5SD6);
    RIFLE(CUP_sgun_Saiga12K, Rifle_Base_F);
    RIFLE(CUP_hgun_BallisticShield_Armed, Rifle_Base_F);
    RIFLE(CUP_srifle_SVD, Rifle_Base_F);
    RIFLE(CUP_srifle_SVD_des, CUP_srifle_SVD);
    RIFLE(CUP_srifle_SVD_des_ghillie_pso, CUP_srifle_SVD);
    RIFLE(CUP_srifle_SVD_wdl_ghillie, CUP_srifle_SVD_des_ghillie_pso);
    RIFLE(CUP_srifle_SVD_pso, CUP_srifle_SVD);
    RIFLE(CUP_srifle_SVD_Des_pso, CUP_srifle_SVD_des);
    RIFLE(CUP_srifle_SVD_NSPU, CUP_srifle_SVD);
    MG(CUP_lmg_UK59, Rifle_Long_Base_F);
    RIFLE(CUP_srifle_VSSVintorez, Rifle_Base_F);
    RIFLE(CUP_srifle_VSSVintorez_pso, CUP_srifle_VSSVintorez);
    PROTO(CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AK47, CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AK74, CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AK74M, CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AK74M_GL, CUP_arifle_AK_Base);
    PROTO(CUP_arifle_AK107_Base);
    RIFLE(CUP_arifle_AK107, CUP_arifle_AK107_Base);
    RIFLE(CUP_arifle_AK107_GL, CUP_arifle_AK107_Base);
    PROTO(CUP_arifle_AKS_Base);
    RIFLE(CUP_arifle_AKS74, CUP_arifle_AKS_Base);
    RIFLE(CUP_arifle_AKS74U, CUP_arifle_AKS_Base);
    RIFLE(CUP_arifle_AK74_GL, CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AKM, CUP_arifle_AK_Base);
    RIFLE(CUP_arifle_AKS, CUP_arifle_AKM);
    RIFLE(CUP_arifle_AKS_Gold, CUP_arifle_AKS);
    RIFLE(CUP_arifle_RPK74, CUP_arifle_AK74);
    RIFLE(CUP_arifle_RPK74_45, CUP_arifle_RPK74);
    RIFLE(CUP_arifle_RPK74M, CUP_arifle_RPK74);
    RIFLE(CUP_arifle_AK107_GL_kobra, CUP_arifle_AK107_GL);
    RIFLE(CUP_arifle_AK107_kobra, CUP_arifle_AK107);
    RIFLE(CUP_arifle_AK107_GL_pso, CUP_arifle_AK107_GL);
    RIFLE(CUP_arifle_AK107_pso, CUP_arifle_AK107);
    RIFLE(CUP_arifle_AKS74_kobra, CUP_arifle_AKS74);
    RIFLE(CUP_arifle_AKS74_pso, CUP_arifle_AKS74);
    RIFLE(CUP_arifle_AKS74UN_kobra_snds, CUP_arifle_AKS74U);
    RIFLE(CUP_arifle_AKS74_Goshawk, CUP_arifle_AKS74);
    RIFLE(CUP_arifle_AKS74_NSPU, CUP_arifle_AKS74);
    RIFLE(CUP_arifle_AK74_GL_kobra, CUP_arifle_AK74_GL);
    RIFLE(CUP_arifle_AKM_snds, CUP_arifle_AKM);
    RIFLE(CUP_arifle_AK74M_GL_kobra, CUP_arifle_AK74M_GL);
    RIFLE(CUP_arifle_AK74M_GL_kobra_snds, CUP_arifle_AK74M_GL);
    RIFLE(CUP_arifle_AK74M_kobra, CUP_arifle_AK74M);
    RIFLE(CUP_arifle_AK74M_kobra_snds, CUP_arifle_AK74M);
    RIFLE(CUP_arifle_AK74M_GL_pso, CUP_arifle_AK74M_GL);
    RIFLE(CUP_arifle_AK74M_pso, CUP_arifle_AK74M);
    RIFLE(CUP_srifle_AS50, Rifle_Long_Base_F);
    RIFLE(CUP_srifle_AS50_SBPMII, CUP_srifle_AS50);
    RIFLE(CUP_srifle_AS50_AMPAS13c2, CUP_srifle_AS50);
    PROTO(CUP_srifle_AWM_Base);
    RIFLE(CUP_srifle_AWM_des, CUP_srifle_AWM_Base);
    RIFLE(CUP_srifle_AWM_wdl, CUP_srifle_AWM_Base);
    RIFLE(CUP_srifle_G22_des, CUP_srifle_AWM_des);
    RIFLE(CUP_srifle_G22_wdl, CUP_srifle_AWM_wdl);
    RIFLE(CUP_srifle_AWM_des_SBPMII, CUP_srifle_AWM_des);
    RIFLE(CUP_srifle_G22_des_SBPMII, CUP_srifle_G22_des);
    RIFLE(CUP_srifle_G22_wdl_SBPMII, CUP_srifle_G22_wdl);
    RIFLE(CUP_srifle_AWM_wdl_SBPMII, CUP_srifle_AWM_wdl);
    MG(CUP_smg_bizon, Rifle_Base_F);
    MG(CUP_smg_bizon_snds, CUP_smg_bizon);
    PROTO(CUP_arifle_CZ805_Base);
    RIFLE(CUP_arifle_CZ805_A2, CUP_arifle_CZ805_Base);
    RIFLE(CUP_arifle_CZ805_A1, CUP_arifle_CZ805_Base);
    RIFLE(CUP_arifle_CZ805_GL, CUP_arifle_CZ805_Base);
    RIFLE(CUP_arifle_CZ805_A2_Holo_Laser, CUP_arifle_CZ805_A2);
    RIFLE(CUP_arifle_CZ805_A1_Holo_Laser, CUP_arifle_CZ805_A1);
    RIFLE(CUP_arifle_CZ805_A2_Aco_Laser, CUP_arifle_CZ805_A2);
    RIFLE(CUP_arifle_CZ805_A1_Aco_Laser, CUP_arifle_CZ805_A1);
    RIFLE(CUP_arifle_CZ805_A1_MRCO_Laser, CUP_arifle_CZ805_A1);
    RIFLE(CUP_arifle_CZ805_A2_MRCO_Laser, CUP_arifle_CZ805_A1);
    RIFLE(CUP_arifle_CZ805_GL_Hamr_Laser, CUP_arifle_CZ805_GL);
    RIFLE(CUP_arifle_CZ805_A1_ZDDot_Laser, CUP_arifle_CZ805_A1);
    RIFLE(CUP_arifle_CZ805_GL_ZDDot_Laser, CUP_arifle_CZ805_GL);
    RIFLE(CUP_arifle_CZ805_A2_ZDDot_Flashlight_Snds, CUP_arifle_CZ805_A2);
    PROTO(CUP_arifle_CZ805_B_Base);
    RIFLE(CUP_arifle_CZ805_B_GL, CUP_arifle_CZ805_B_Base);
    RIFLE(CUP_arifle_CZ805_B, CUP_arifle_CZ805_B_Base);
    RIFLE(CUP_arifle_CZ805B_GL_ACOG_Laser, CUP_arifle_CZ805_B_GL);
    RIFLE(CUP_smg_EVO, Rifle_Base_F);
    RIFLE(CUP_smg_EVO_MRad_Flashlight, CUP_smg_EVO);
    RIFLE(CUP_smg_EVO_MRad_Flashlight_Snds, CUP_smg_EVO);
    RIFLE(CUP_arifle_FNFAL, Rifle_Base_F);
    RIFLE(CUP_arifle_FNFAL5061, CUP_arifle_FNFAL);
    RIFLE(CUP_arifle_FNFAL5062, CUP_arifle_FNFAL);
    RIFLE(CUP_arifle_FNFAL_OSW, CUP_arifle_FNFAL);
    RIFLE(CUP_arifle_FNFAL_railed, CUP_arifle_FNFAL);
    RIFLE(CUP_arifle_FNFAL_ANPVS4, CUP_arifle_FNFAL_railed);
    PROTO(CUP_arifle_G36_Base);
    RIFLE(CUP_arifle_G36A, CUP_arifle_G36_Base);
    RIFLE(CUP_arifle_G36A_camo, CUP_arifle_G36A);
    RIFLE(CUP_arifle_G36K, CUP_arifle_G36A);
    RIFLE(CUP_arifle_G36K_camo, CUP_arifle_G36K);
    RIFLE(CUP_arifle_G36C, Rifle_Base_F);
    RIFLE(CUP_arifle_G36C_camo, CUP_arifle_G36C);
    RIFLE(CUP_arifle_MG36, CUP_arifle_G36C);
    RIFLE(CUP_arifle_MG36_camo, CUP_arifle_MG36);
    RIFLE(CUP_arifle_G36C_holo_snds, CUP_arifle_G36C);
    RIFLE(CUP_arifle_G36C_camo_holo_snds, CUP_arifle_G36C_camo);
    RIFLE(CUP_arifle_MG36_holo, CUP_arifle_MG36);
    RIFLE(CUP_arifle_MG36_camo_holo, CUP_arifle_MG36_camo);
    RIFLE(CUP_lmg_L110A1, Rifle_Long_Base_F);
    RIFLE(CUP_lmg_L110A1_Aim_Laser, CUP_lmg_L110A1);
    RIFLE(CUP_srifle_L129A1, Rifle_Base_F);
    RIFLE(CUP_srifle_L129A1_HG, CUP_srifle_L129A1);
    PROTO(CUP_l85a2);
    RIFLE(CUP_arifle_L85A2, CUP_l85a2);
    PROTO(CUP_l85a2_ris);
    RIFLE(CUP_arifle_L85A2_G, CUP_l85a2_ris);
    PROTO(CUP_l85a2_ris_ng);
    RIFLE(CUP_arifle_L85A2_NG, CUP_l85a2_ris_ng);
    PROTO(CUP_l85a2_ugl);
    RIFLE(CUP_arifle_L85A2_GL, CUP_l85a2_ugl);
    RIFLE(CUP_arifle_L86A2, CUP_l85a2);
    RIFLE(CUP_arifle_L85A2_Holo_laser, CUP_arifle_L85A2_G);
    RIFLE(CUP_arifle_L85A2_GL_Holo_Laser, CUP_arifle_L85A2_GL);
    RIFLE(CUP_arifle_L85A2_SUSAT_Laser, CUP_arifle_L85A2_G);
    RIFLE(CUP_arifle_L85A2_GL_SUSAT_Laser, CUP_arifle_L85A2_GL);
    RIFLE(CUP_arifle_L85A2_CWS_Laser, CUP_arifle_L85A2_G);
    RIFLE(CUP_arifle_L85A2_ACOG_Laser, CUP_arifle_L85A2_G);
    RIFLE(CUP_arifle_L85A2_GL_ACOG_Laser, CUP_arifle_L85A2_GL);
    RIFLE(CUP_arifle_L86A2_ACOG, CUP_arifle_L86A2);
    RIFLE(CUP_sgun_M1014, Rifle_Base_F);
    RIFLE(CUP_srifle_M107_Base, Rifle_Long_Base_F);
    RIFLE(CUP_srifle_M107_LeupoldVX3, CUP_srifle_M107_Base);
    RIFLE(CUP_srifle_M107_ANPAS13c2, CUP_srifle_M107_Base);
    RIFLE(CUP_srifle_M110, Rifle_Base_F);
    RIFLE(CUP_srifle_M110_ANPAS13c2, CUP_srifle_M110);
    RIFLE(CUP_srifle_M110_ANPVS10, CUP_srifle_M110);
    RIFLE(CUP_srifle_M14, Rifle_Base_F);
    RIFLE(CUP_srifle_M14_CCO, CUP_srifle_M14);
    PROTO(CUP_arifle_M16_Base);
    RIFLE(CUP_arifle_M16A2, CUP_arifle_M16_Base);
    RIFLE(CUP_arifle_M16A2_GL, CUP_arifle_M16_Base);
    RIFLE(CUP_arifle_M16A4_Base, CUP_arifle_M16_Base);
    RIFLE(CUP_arifle_M16A4_GL, CUP_arifle_M16_Base);
    RIFLE(CUP_arifle_M16A4_Aim_Laser, CUP_arifle_M16A4_Base);
    RIFLE(CUP_arifle_M16A4_ACOG_Laser, CUP_arifle_M16A4_Base);
    RIFLE(CUP_arifle_M16A4_GL_Laser, CUP_arifle_M16A4_GL);
    RIFLE(CUP_arifle_M16A4_GL_ACOG_Laser, CUP_arifle_M16A4_GL);
    PROTO(CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_BUIS_GL, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_BUIS_camo_GL, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_BUIS_desert_GL, CUP_arifle_M4A1_BUIS_Base);
    PROTO(CUP_arifle_M4_Base);
    RIFLE(CUP_arifle_M4A1, CUP_arifle_M4_Base);
    RIFLE(CUP_arifle_M4A1_camo, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_black, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_desert, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A3_desert, CUP_arifle_M4A1_BUIS_Base);
    RIFLE(CUP_arifle_M4A1_camo_Aim, CUP_arifle_M4A1_camo);
    RIFLE(CUP_arifle_M4A3_desert_Aim_Flashlight, CUP_arifle_M4A1_desert);
    RIFLE(CUP_arifle_M4A3_desert_GL_ACOG_Laser, CUP_arifle_M4A1_BUIS_desert_GL);
    RIFLE(CUP_arifle_M4A1_Aim, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_camo_AIM_snds, CUP_arifle_M4A1_camo);
    RIFLE(CUP_arifle_M4A1_GL_Holo_Flashlight, CUP_arifle_M4A1_BUIS_GL);
    RIFLE(CUP_arifle_M4A1_GL_ACOG_Flashlight, CUP_arifle_M4A1_BUIS_GL);
    RIFLE(CUP_arifle_M4A1_camo_GL_Holo_Flashlight, CUP_arifle_M4A1_BUIS_camo_GL);
    RIFLE(CUP_arifle_M4A1_camo_GL_Holo_Flashlight_Snds, CUP_arifle_M4A1_BUIS_camo_GL);
    RIFLE(CUP_srifle_Mk12SPR, CUP_arifle_M4A1);
    RIFLE(CUP_srifle_Mk12SPR_LeupoldM3LR, CUP_srifle_Mk12SPR);
    RIFLE(CUP_srifle_Mk12SPR_LeupoldM3LR_bipod, CUP_srifle_Mk12SPR);
    RIFLE(CUP_arifle_M4A1_LeupoldMk4MRT, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_Aim_Laser_snds, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_M203_Holo_Laser, CUP_arifle_M4A1_BUIS_GL);
    RIFLE(CUP_arifle_M4A1_Holo, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_M203_ACOG_Laser, CUP_arifle_M4A1_BUIS_GL);
    RIFLE(CUP_arifle_M4A1_M203_ANPAS13c1_Laser, CUP_arifle_M4A1_BUIS_GL);
    RIFLE(CUP_arifle_M4A1_Holo_Laser, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_LeupoldMk4CQT_Laser, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_ACOG_Laser, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_ACOG_flashlight, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_CCO_Laser, CUP_arifle_M4A1_black);
    RIFLE(CUP_arifle_M4A1_CCO_flashlight, CUP_arifle_M4A1_black);
    PROTO(CUP_saw_base);
    RIFLE(CUP_lmg_minimipara, CUP_saw_base);
    RIFLE(CUP_lmg_minimi, CUP_lmg_minimipara);
    RIFLE(CUP_lmg_m249_para, CUP_lmg_minimipara);
    RIFLE(CUP_lmg_M249_E2, CUP_lmg_minimipara);
    RIFLE(CUP_lmg_minimi_railed, CUP_lmg_minimipara);
    RIFLE(CUP_lmg_m249_pip1, CUP_lmg_minimi_railed);
    RIFLE(CUP_lmg_m249_pip2, CUP_lmg_minimi_railed);
    RIFLE(CUP_lmg_m249_pip3, CUP_lmg_minimi_railed);
    RIFLE(CUP_lmg_m249_pip4, CUP_lmg_minimi_railed);
    RIFLE(CUP_lmg_m249_SQuantoon, CUP_lmg_m249_pip4);
    RIFLE(CUP_lmg_m249_para_gl, CUP_lmg_minimipara);
    RIFLE(CUP_lmg_M249_ElcanM145_Laser, CUP_lmg_m249_pip4);
    RIFLE(CUP_lmg_M249_Laser, CUP_lmg_m249_pip4);
    RIFLE(CUP_lmg_M249_ANPAS13c2_Laser, CUP_lmg_m249_pip4);
    PROTO(CUP_M60E4_base);
    MG(CUP_lmg_M60E4, CUP_M60E4_base);
    PROTO(CUP_lmg_Mk48_Base);
    MG(CUP_lmg_Mk48_des, CUP_lmg_Mk48_Base);
    MG(CUP_lmg_Mk48_wdl, CUP_lmg_Mk48_Base);
    MG(CUP_lmg_Mk48_des_Aim_Laser, CUP_lmg_Mk48_des);
    MG(CUP_lmg_Mk48_wdl_Aim_Laser, CUP_lmg_Mk48_wdl);
    MG(CUP_lmg_PKM, Rifle_Long_Base_F);
    MG(CUP_lmg_Pecheneg, CUP_lmg_PKM);
    MG(CUP_lmg_Pecheneg_PScope, CUP_lmg_Pecheneg);
    PROTO(CUP_arifle_Sa58_base);
    RIFLE(CUP_arifle_Sa58P, CUP_arifle_Sa58_base);
    RIFLE(CUP_arifle_Sa58P_des, CUP_arifle_Sa58P);
    RIFLE(CUP_arifle_Sa58V, CUP_arifle_Sa58P);
    RIFLE(CUP_arifle_Sa58V_camo, CUP_arifle_Sa58V);
    RIFLE(CUP_arifle_Sa58RIS1, CUP_arifle_Sa58_base);
    RIFLE(CUP_arifle_Sa58RIS2_gl, CUP_arifle_Sa58RIS1);
    RIFLE(CUP_arifle_Sa58RIS1_des, CUP_arifle_Sa58RIS1);
    RIFLE(CUP_arifle_Sa58RIS2, CUP_arifle_Sa58RIS1);
    RIFLE(CUP_arifle_Sa58RIS2_camo, CUP_arifle_Sa58RIS2);
    RIFLE(CUP_arifle_Sa58RIS1_Aco_Laser, CUP_arifle_Sa58RIS1);
    RIFLE(CUP_arifle_Sa58RIS2_Arco_Laser, CUP_arifle_Sa58RIS2);
    RIFLE(CUP_arifle_Sa58RIS1_camo_Aco_Laser, CUP_arifle_Sa58RIS1_des);
    RIFLE(CUP_arifle_Sa58RIS2_camo_Arco_Laser, CUP_arifle_Sa58RIS2_camo);
    RIFLE(CUP_arifle_Sa58V_ACOG_Laser, CUP_arifle_Sa58V);
    RIFLE(CUP_arifle_Sa58V_Aim_Laser, CUP_arifle_Sa58V);
    PROTO(CUP_arifle_SCAR_L_Base);
    RIFLE(CUP_arifle_Mk16_CQC, CUP_arifle_SCAR_L_Base);
    RIFLE(CUP_arifle_Mk16_CQC_FG, CUP_arifle_Mk16_CQC);
    RIFLE(CUP_arifle_Mk16_CQC_SFG, CUP_arifle_Mk16_CQC);
    RIFLE(CUP_arifle_Mk16_CQC_EGLM, CUP_arifle_Mk16_CQC);
    RIFLE(CUP_arifle_Mk16_STD, CUP_arifle_SCAR_L_Base);
    RIFLE(CUP_arifle_Mk16_STD_FG, CUP_arifle_Mk16_STD);
    RIFLE(CUP_arifle_Mk16_STD_SFG, CUP_arifle_Mk16_STD);
    RIFLE(CUP_arifle_Mk16_STD_EGLM, CUP_arifle_Mk16_STD);
    RIFLE(CUP_arifle_Mk16_SV, CUP_arifle_SCAR_L_Base);
    RIFLE(CUP_arifle_Mk16_LeupoldMk4MRT, CUP_arifle_Mk16_SV);
    RIFLE(CUP_arifle_Mk16_CQC_FG_Aim_Laser_snds, CUP_arifle_Mk16_CQC_FG);
    RIFLE(CUP_arifle_Mk16_CQC_EGLM_Holo_Laser_mfsup, CUP_arifle_Mk16_CQC_EGLM);
    RIFLE(CUP_arifle_Mk16_CQC_SFG_Holo, CUP_arifle_Mk16_CQC_SFG);
    RIFLE(CUP_arifle_Mk16_STD_EGLM_ACOG_Laser, CUP_arifle_Mk16_STD_EGLM);
    RIFLE(CUP_arifle_Mk16_STD_EGLM_ANPAS13c1_Laser_mfsup, CUP_arifle_Mk16_STD_EGLM);
    RIFLE(CUP_arifle_Mk16_STD_FG_Holo_Laser, CUP_arifle_Mk16_STD_FG);
    RIFLE(CUP_arifle_Mk16_STD_FG_LeupoldMk4CQT_Laser, CUP_arifle_Mk16_STD_FG);
    PROTO(CUP_arifle_Mk17_Base);
    RIFLE(CUP_arifle_Mk17_CQC, CUP_arifle_Mk17_Base);
    RIFLE(CUP_arifle_Mk17_CQC_FG, CUP_arifle_Mk17_CQC);
    RIFLE(CUP_arifle_Mk17_CQC_SFG, CUP_arifle_Mk17_CQC_FG);
    RIFLE(CUP_arifle_Mk17_CQC_EGLM, CUP_arifle_Mk17_CQC);
    RIFLE(CUP_arifle_Mk17_STD, CUP_arifle_Mk17_Base);
    RIFLE(CUP_arifle_Mk17_STD_FG, CUP_arifle_Mk17_STD);
    RIFLE(CUP_arifle_Mk17_STD_SFG, CUP_arifle_Mk17_STD_FG);
    RIFLE(CUP_arifle_Mk17_STD_EGLM, CUP_arifle_Mk17_STD);
    RIFLE(CUP_arifle_Mk20, CUP_arifle_Mk17_Base);
    RIFLE(CUP_arifle_Mk17_CQC_SFG_Aim_mfsup, CUP_arifle_Mk17_CQC_SFG);
    RIFLE(CUP_arifle_Mk17_STD_FG_Aim_Laser_snds, CUP_arifle_Mk17_CQC_FG);
    RIFLE(CUP_arifle_Mk17_STD_EGL_ElcanSpecter_Laser, CUP_arifle_Mk17_CQC_EGLM);
    RIFLE(CUP_arifle_Mk17_STD_FG_ANPAS13c1_Laser_Snds, CUP_arifle_Mk17_STD_FG);
    RIFLE(CUP_arifle_Mk20_LeupoldMk4MRT, CUP_arifle_Mk20);
    RIFLE(CUP_arifle_Mk20_SB11420_snds, CUP_arifle_Mk20);
    RIFLE(CUP_arifle_Mk16_CQC_woodland, CUP_arifle_Mk16_CQC);
    RIFLE(CUP_arifle_Mk16_CQC_FG_woodland, CUP_arifle_Mk16_CQC_FG);
    RIFLE(CUP_arifle_Mk16_CQC_SFG_woodland, CUP_arifle_Mk16_CQC_SFG);
    RIFLE(CUP_arifle_Mk16_CQC_EGLM_woodland, CUP_arifle_Mk16_CQC_EGLM);
    RIFLE(CUP_arifle_Mk16_STD_woodland, CUP_arifle_Mk16_STD);
    RIFLE(CUP_arifle_Mk16_STD_FG_woodland, CUP_arifle_Mk16_STD_FG);
    RIFLE(CUP_arifle_Mk16_STD_SFG_woodland, CUP_arifle_Mk16_STD_SFG);
    RIFLE(CUP_arifle_Mk16_STD_EGLM_woodland, CUP_arifle_Mk16_STD_EGLM);
    RIFLE(CUP_arifle_Mk16_SV_woodland, CUP_arifle_Mk16_SV);
    RIFLE(CUP_arifle_Mk17_CQC_woodland, CUP_arifle_Mk17_CQC);
    RIFLE(CUP_arifle_Mk17_CQC_FG_woodland, CUP_arifle_Mk17_CQC_FG);
    RIFLE(CUP_arifle_Mk17_CQC_SFG_woodland, CUP_arifle_Mk17_CQC_SFG);
    RIFLE(CUP_arifle_Mk17_CQC_EGLM_woodland, CUP_arifle_Mk17_CQC_EGLM);
    RIFLE(CUP_arifle_Mk17_STD_woodland, CUP_arifle_Mk17_STD);
    RIFLE(CUP_arifle_Mk17_STD_FG_woodland, CUP_arifle_Mk17_STD_FG);
    RIFLE(CUP_arifle_Mk17_STD_SFG_woodland, CUP_arifle_Mk17_STD_SFG);
    RIFLE(CUP_arifle_Mk17_STD_EGLM_woodland, CUP_arifle_Mk17_STD_EGLM);
    RIFLE(CUP_arifle_Mk16_CQC_black, CUP_arifle_Mk16_CQC);
    RIFLE(CUP_arifle_Mk16_CQC_FG_black, CUP_arifle_Mk16_CQC_FG);
    RIFLE(CUP_arifle_Mk16_CQC_SFG_black, CUP_arifle_Mk16_CQC_SFG);
    RIFLE(CUP_arifle_Mk16_CQC_EGLM_black, CUP_arifle_Mk16_CQC_EGLM);
    RIFLE(CUP_arifle_Mk16_STD_black, CUP_arifle_Mk16_STD);
    RIFLE(CUP_arifle_Mk16_STD_FG_black, CUP_arifle_Mk16_STD_FG);
    RIFLE(CUP_arifle_Mk16_STD_SFG_black, CUP_arifle_Mk16_STD_SFG);
    RIFLE(CUP_arifle_Mk16_STD_EGLM_black, CUP_arifle_Mk16_STD_EGLM);
    RIFLE(CUP_arifle_Mk16_SV_black, CUP_arifle_Mk16_SV);
    RIFLE(CUP_arifle_Mk17_CQC_Black, CUP_arifle_Mk17_CQC);
    RIFLE(CUP_arifle_Mk17_CQC_FG_black, CUP_arifle_Mk17_CQC_FG);
    RIFLE(CUP_arifle_Mk17_CQC_SFG_black, CUP_arifle_Mk17_CQC_SFG);
    RIFLE(CUP_arifle_Mk17_CQC_EGLM_black, CUP_arifle_Mk17_CQC_EGLM);
    RIFLE(CUP_arifle_Mk17_STD_black, CUP_arifle_Mk17_STD);
    RIFLE(CUP_arifle_Mk17_STD_FG_black, CUP_arifle_Mk17_STD_FG);
    RIFLE(CUP_arifle_Mk17_STD_SFG_black, CUP_arifle_Mk17_STD_SFG);
    RIFLE(CUP_arifle_Mk17_STD_EGLM_black, CUP_arifle_Mk17_STD_EGLM);
    PROTO(CUP_arifle_XM8_Base);
    RIFLE(CUP_arifle_XM8_Carbine, CUP_arifle_XM8_Base);
    RIFLE(CUP_arifle_XM8_Carbine_GL, CUP_arifle_XM8_Base);
    RIFLE(CUP_arifle_xm8_sharpshooter, CUP_arifle_XM8_Base);
    RIFLE(CUP_arifle_xm8_SAW, CUP_arifle_xm8_sharpshooter);
    RIFLE(CUP_arifle_XM8_Compact, CUP_arifle_XM8_Base);
    RIFLE(CUP_arifle_XM8_Compact_Rail, CUP_arifle_XM8_Compact);
    RIFLE(CUP_arifle_XM8_Compact_Holo_Flashlight, CUP_arifle_XM8_Compact_Rail);
    PROTO(CUP_arifle_XM8_Railed_Base);
    RIFLE(CUP_arifle_XM8_Railed, CUP_arifle_XM8_Railed_Base);
    RIFLE(CUP_arifle_XM8_Railed_ANPAS13c1_Laser, CUP_arifle_XM8_Railed);
    RIFLE(CUP_arifle_XM8_Railed_ANPAS13c1_Laser_snds, CUP_arifle_XM8_Railed);
    RIFLE(CUP_arifle_XM8_Railed_Holo_Laser_snds, CUP_arifle_XM8_Railed);
    RIFLE(CUP_arifle_XM8_Carbine_FG, CUP_arifle_XM8_Base);
    RIFLE(B_Patrol_Soldier_Autorifleman_weapon_F, arifle_MX_SW_F);
    RIFLE(B_Patrol_Soldier_Carrier_weapon_F, arifle_MX_F);
    MG(B_Patrol_Soldier_HeavyGunner_weapon_F, LMG_Zafir_F);
    RIFLE(B_Patrol_Soldier_Leader_weapon_F, arifle_MX_GL_F);
    MG(B_Patrol_Soldier_MachineGunner_weapon_F, LMG_Mk200_F);
    RIFLE(B_Patrol_Soldier_Marksman_weapon_F, srifle_EBR_F);
    RIFLE(B_Patrol_Soldier_Medic_weapon_F, arifle_MX_F);
    RIFLE(B_Patrol_Soldier_Operator_weapon_F, arifle_MXC_F);
    RIFLE(B_Patrol_Soldier_Specialist_weapon_F, arifle_MX_F);
};
