class CfgPatches {
    class arc_ai_main {
        ammo[] = {};
        units[] = {};
        weapons[] = {};
        requiredVersion = 1.54;
        author[] = {"Ed", "Kingsley"};
        authorUrl = "https://github.com/ARCOMM/ARC_AI";
        requiredAddons[] = {
            "A3_Weapons_F",
            "A3_Weapons_F_Items",
            "A3_Weapons_F_Launchers_NLAW",
            "A3_Weapons_F_Launchers_RPG32",
            "A3_Weapons_F_Launchers_Titan",
            "A3_Weapons_F_LongRangeRifles_DMR_01",
            "A3_Weapons_F_LongRangeRifles_EBR",
            "A3_Weapons_F_LongRangeRifles_GM6",
            "A3_Weapons_F_LongRangeRifles_M320",
            "A3_Weapons_F_Machineguns_M200",
            "A3_Weapons_F_Machineguns_Zafir",
            "A3_Weapons_F_Pistols_ACPC2",
            "A3_Weapons_F_Pistols_P07",
            "A3_Weapons_F_Pistols_Pistol_Heavy_01",
            "A3_Weapons_F_Pistols_Pistol_Heavy_02",
            "A3_Weapons_F_Pistols_Rook40",
            "A3_Weapons_F_Rifles_Khaybar",
            "A3_Weapons_F_Rifles_MK20",
            "A3_Weapons_F_Rifles_MX",
            "A3_Weapons_F_Rifles_MX_Black",
            "A3_Weapons_F_Rifles_SDAR",
            "A3_Weapons_F_Rifles_TRG20",
            "A3_Weapons_F_SMGs_Pdw2000",
            "A3_Weapons_F_SMGs_SMG_01",
            "A3_Weapons_F_SMGs_SMG_02",
            "A3_Characters_F",
            "A3_Weapons_F_Acc",
            "arc_flashlights",
            "Clarks_AOR_Uniforms",
            "Clarks_Russian_Uniforms",
            "CUP_CWA_Misc",
            "A3_Drones_F_Weapons_F_Gamma_Items",
            "rhsusf_c_heavyweapons",
            "A3_Data_F_Curator",
            "A3_Data_F_Curator_Virtual",
            "rhsusf_c_airweapons",
            "A3_Weapons_F_Kart_Pistols_Pistol_Signal_F",
            "A3_Weapons_F_Mark",
            "A3_Weapons_F_Mark_Acc",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_01",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_02",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_03",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_04",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_05",
            "A3_Weapons_F_Mark_LongRangeRifles_DMR_06",
            "A3_Weapons_F_Mark_LongRangeRifles_EBR",
            "A3_Weapons_F_Mark_Machineguns_M200",
            "A3_Weapons_F_Mark_Machineguns_MMG_01",
            "A3_Weapons_F_Mark_Machineguns_MMG_02",
            "A3_Weapons_F_Mark_Rifles_MX",
            "rhs_c_heavyweapons",
            "rhs_c_weapons",
            "rhsusf_c_weapons",
            "A3_Weapons_F_Exp",
            "A3_Weapons_F_Exp_Launchers_RPG32",
            "A3_Weapons_F_Exp_Launchers_RPG7",
            "A3_Weapons_F_Exp_Launchers_Titan",
            "A3_Weapons_F_Exp_LongRangeRifles_DMR_07",
            "A3_Weapons_F_Exp_Machineguns_LMG_03",
            "A3_Weapons_F_Exp_Pistols_Pistol_01",
            "A3_Weapons_F_Exp_Rifles_AK12",
            "A3_Weapons_F_Exp_Rifles_AKM",
            "A3_Weapons_F_Exp_Rifles_AKS",
            "A3_Weapons_F_Exp_Rifles_ARX",
            "A3_Weapons_F_Exp_Rifles_CTAR",
            "A3_Weapons_F_Exp_Rifles_CTARS",
            "A3_Weapons_F_Exp_Rifles_SPAR_01",
            "A3_Weapons_F_Exp_Rifles_SPAR_02",
            "A3_Weapons_F_Exp_Rifles_SPAR_03",
            "A3_Weapons_F_Exp_SMGs_SMG_05",
            "rhs_c_troops",
            "rhsusf_c_troops",
            "A3_Characters_F_Exp",
            "A3_Characters_F_Exp_Headgear",
            "A3_Characters_F_Exp_Vests",
            "rhs_c_rva",
            "rhsusf_c_mrzr",
            "A3_Weapons_F_Jets",
            "A3_Characters_F_Jets_Vests",
            "A3_Weapons_F_Patrol",
            "A3_Weapons_F_Orange",
            "A3_Weapons_F_Orange_Items",
            "A3_Characters_F_Orange",
            "A3_Characters_F_Orange_Headgear",
            "A3_Characters_F_Orange_Vests",
            "ace_ai"
        };
    };
};
